### ISSUE TITLE
建议-是否可以支持 Little Snitch

### ISSUE THREAD

**Issue by greswt** [QiuChenlyOpenSource/InjectLib#1]
开发者你好，请问是否可以尝试支持Little Snitch的版本限制？版本是5.6
<img width="266" alt="截屏2023-06-10 21 42 43" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/104300237/7f68ab60-bf25-444a-a825-e0b888a22795">
<img width="854" alt="截屏2023-06-10 21 43 10" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/104300237/f9e2d004-bdcf-435b-86af-884b392b7328">

**Comment by QiuChenly** [comment]
暂无计划
