### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hanchiatw** [QiuChenlyOpenSource/InjectLib#10]
執行時報錯
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ./Utils (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/hanchia/Desktop/InjectLib-main/main.rb:3:in `<main>'

**Comment by QiuChenly** [comment]
要从终端进入这个文件夹内执行。
