### ISSUE TITLE
tableplus破解后关键字自动补全会添加 ` 符号

### ISSUE THREAD

**Issue by MrChenSH** [QiuChenlyOpenSource/InjectLib#114]
tableplus破解后关键字自动补全会添加 ` 符号，官方试用版无此问题，版本：5.5.2 (512)，CPU是Intel的
还请大神看看什么原因

<img width="913" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/8321157/93d33a6b-0f83-4d16-b748-5b8ecc0eba5f">

正常情况应该是这样的

<img width="318" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/8321157/ca9c73bc-3c5d-44e2-8569-9d585798367e">

**Comment by smomop** [comment]
arm架构也存在这个这个，自动添加双引号

**Comment by QiuChenly** [comment]
建议放弃TablePlus
如果是怕律师函 可以用DataGrip

**Comment by PataPon-coder** [comment]
同遇到了 解决了吗

**Comment by zhouJianXXX** [comment]
同问，实在太恼人了

**Comment by zhouJianXXX** [comment]
同样的问题，实在太恼人了

**Comment by suhang12332** [comment]
偶然看到有人说的这个

<img width="597" alt="QQ20240207-164319@2x" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/48873455/92c97916-e275-4bd8-9cf5-b71b844517cb">

[某个网站的帖子](https://www.52pojie.cn/thread-1881366-1-1.html)

**Comment by smomop** [comment]
> 偶然看到有人说的这个
> 
> 
> 
> <img width="597" alt="QQ20240207-164319@2x" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/48873455/92c97916-e275-4bd8-9cf5-b71b844517cb">
> 
> 
> 
> [某个网站的帖子](https://www.52pojie.cn/thread-1881366-1-1.html)
> 
> 
> 
> 

用这个帖子里的方法已经完美破解了

**Comment by suhang12332** [comment]
@smomop 怎么搞,我能加你的qq吗,我想咨询一下细节..或者 您加我 1552899301 这是我的qq
