### ISSUE TITLE
Navicat Premium16.2.9 破解后无法通过SSH Tunnel连接

### ISSUE THREAD

**Issue by smoothdvd** [QiuChenlyOpenSource/InjectLib#115]
<img width="886" alt="Screenshot 2023-10-27 at 12 18 24 AM" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/22420/cb74e61f-80d3-4572-8d84-db9cdb0e23e0">

不使用SSH Tunnel的本地连接正常。

**Comment by QiuChenly** [comment]
这可能不是破解的问题。建议再查查资料。
