### ISSUE TITLE
Omi录屏专家 v1.3.3 破解后屏幕录制权限开启应用提示失败

### ISSUE THREAD

**Issue by xzygreen** [QiuChenlyOpenSource/InjectLib#117]
Omi录屏专家 v1.3.3 破解后屏幕录制权限开启应用提示失败，无错误日志。没破解时正常
测试环境：macos14
<img width="980" alt="截屏2023-10-28 13 04 18" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/125412114/2f0b2d9b-3163-4a2c-89ff-bf06015a0daa">

日志
[screen_recorder.log](https://github.com/QiuChenlyOpenSource/InjectLib/files/13194542/screen_recorder.log)

**Comment by xzygreen** [comment]
还不行

**Comment by QiuChenly** [comment]
怎么操作的？

**Comment by QiuChenly** [comment]
tccutil reset Camera com.mac.utility.screen.recorder
tccutil reset Microphone com.mac.utility.screen.recorder
tccutil reset ScreenCapture com.mac.utility.screen.recorder

**Comment by QiuChenly** [comment]
自己执行，macOS权限系统bug。

**Comment by xzygreen** [comment]
tccutil reset Camera com.mac.utility.screen.recorder
tccutil reset Microphone com.mac.utility.screen.recorder
tccutil reset ScreenCapture com.mac.utility.screen.recorder

这个成功了，感谢
