### ISSUE TITLE
是不是每次开机都要从新激活通过Surge激活的app?

### ISSUE THREAD

**Issue by JianGuo1528** [QiuChenlyOpenSource/InjectLib#118]
使用Surge脚本成功激活了AlDente pro.
但是每次重新开机都需要重新激活AlDente pro, 这是正常所需要进行的操作吗？

**Comment by QiuChenly** [comment]
你知不知道人家软件有网络验证啊
你得一直开着Surge才行啊 你不会以为激活一次就不用激活了吧

**Comment by JianGuo1528** [comment]
我Surge是开机自动启动的.

**Comment by QiuChenly** [comment]
那就说明改了验证了  这种办法只能激活一些没有加强验证的App
