### ISSUE TITLE
CleanMyMac 失败，详情如下

### ISSUE THREAD

**Issue by AvaTaylor121** [QiuChenlyOpenSource/InjectLib#119]
问题：运行后没报错，但点开软件后没成功。
环境：
  系统：macOS 13.4
  硬件：MacBook Pro  13-inch, 2020, Two Thunderbolt 3 ports
  CleanMyMac X：4.14.4  
  原神：1.2
操作：
 双击原神启动，找到到对应软件后，开始执行
![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/143675654/0ac722ad-732d-4672-8ffe-3a44130fceb8)

说明：CleanMyMac 是从 readme 上地址下载的。
不知道是自己操作问题还是其他问题，期待大佬解答，感谢大佬

**Comment by QiuChenly** [comment]
啥叫不行？

**Comment by xzygreen** [comment]
cleanmymac x menu 也要注入

**Comment by AvaTaylor121** [comment]
> 啥叫不行？

就是还是未解锁
<img width="1263" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/143675654/7892ac31-02f0-45ce-b31d-dbfc598af69e">
彻底删除后，又重新运行原神，不知道是不是第一张图的报错导致的。
![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/143675654/3b9a052d-f618-43b5-9c05-7f2d69145049)
![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/143675654/3a83e343-5b9d-4e5d-8215-07cb5522fa0d)

**Comment by AvaTaylor121** [comment]
> cleanmymac x menu 也要注入 <img alt="截屏2023-10-31 10 15 03" width="726" src="https://user-images.githubusercontent.com/125412114/279239133-53721716-1214-41f9-ba8c-371ba6c723a6.png"> 别下大陆特供版 用这个https://dl.devmate.com/com.macpaw.CleanMyMac4/CleanMyMacX.dmg

使用了大佬提供的安装包，menu也注入了，还是未解锁。

**Comment by xzygreen** [comment]
那你重新下一下仓库 https://github.com/QiuChenlyOpenSource/InjectLib/archive/refs/heads/main.zip

**Comment by QiuChenly** [comment]
讲道理 这种啥b软件我都不爱用

**Comment by AvaTaylor121** [comment]
> 那你重新下一下仓库 https://github.com/QiuChenlyOpenSource/InjectLib/archive/refs/heads/main.zip 把现在的那个文件夹替换一下

还是一样😭

**Comment by AvaTaylor121** [comment]
> 讲道理 这种啥b软件我都不爱用

大佬有什么推荐吗，整理硬盘和卸载相关的

**Comment by QiuChenly** [comment]
<img width="395" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/24793281/4af3c834-7e81-47bd-a2f4-19289885cdf2">
我软件列表都有啊

**Comment by QiuChenly** [comment]
CMMX只会把我电脑变得无缘无故发热 卡顿 后台扫描进程无时无刻都在进行CPU占用 纯垃圾

**Comment by AvaTaylor121** [comment]
> <img alt="image" width="395" src="https://user-images.githubusercontent.com/24793281/279265600-4af3c834-7e81-47bd-a2f4-19289885cdf2.png"> 我软件列表都有啊

确实有点发热，好的大佬，我试试新的，感谢大佬

**Comment by QiuChenly** [comment]
已为CMMX 4.14.4更新补丁。

**Comment by AvaTaylor121** [comment]
> 已为CMMX 4.14.4更新补丁。

感谢，那我就测试下

**Comment by AvaTaylor121** [comment]
注入成功 感谢大佬@QiuChenly
