### ISSUE TITLE
请教Surge Pro下载点问题

### ISSUE THREAD

**Issue by fourcute** [QiuChenlyOpenSource/InjectLib#12]
请教哪里可以找到您需要的版本？

官网文字（下载回来是5.1.1）
Starting today, you can manually download and start using Surge Mac 5.0, download link: https://dl.nssurge.com/mac/v5/Surge-latest.zip

**Comment by ertcds** [comment]
我下载的5.1版本，注入后，授权正确，但是不能用，节点全部超时，不知道是不是版本不对

**Comment by digitalhouse** [comment]
> 請教哪裡可以找到您需要的版本？
> 
> 官網文字（下載回來是5.1.1） Starting today, you can manually download and start using Surge Mac 5.0, download link: https://dl.nssurge.com/mac/v5/Surge-latest.zip

要去設定裡面打開beta版更新

**Comment by fourcute** [comment]
> > 請教哪裡可以找到您需要的版本？
> > 官網文字（下載回來是5.1.1） Starting today, you can manually download and start using Surge Mac 5.0, download link: https://dl.nssurge.com/mac/v5/Surge-latest.zip
> 
> 要去設定裡面打開beta版更新

感谢这位师兄

**Comment by ertcds** [comment]
> > > 請教哪裡可以找到您需要的版本？
> > > 官網文字（下載回來是5.1.1） Starting today, you can manually download and start using Surge Mac 5.0, download link: https://dl.nssurge.com/mac/v5/Surge-latest.zip
> > 
> > 
> > 要去設定裡面打開beta版更新
> 
> 感谢这位师兄

你更新后可以注入吗？我的版本对了，但是提示不支持的版本？

**Comment by digitalhouse** [comment]
> > > > 請教哪裡可以找到您需要的版本？
> > > > 官網文字（下載回來是5.1.1） Starting today, you can manually download and start using Surge Mac 5.0, download link: https://dl.nssurge.com/mac/v5/Surge-latest.zip
> > > 
> > > 
> > > 要去設定裡面打開beta版更新
> > 
> > 
> > 感謝這位師兄
> 
> 你更新後可以注入嗎？我的版本對了，但是提示不支援的版本？

我的目前版本5.2.0(2269)破解使用正常

應該是你沒有git pull更新同步新版破解吧？

**Comment by ertcds** [comment]
> > > > > 請教哪裡可以找到您需要的版本？
> > > > > 官網文字（下載回來是5.1.1） Starting today, you can manually download and start using Surge Mac 5.0, download link: https://dl.nssurge.com/mac/v5/Surge-latest.zip
> > > > 
> > > > 
> > > > 要去設定裡面打開beta版更新
> > > 
> > > 
> > > 感謝這位師兄
> > 
> > 
> > 你更新後可以注入嗎？我的版本對了，但是提示不支援的版本？
> 
> 我的目前版本5.2.0(2269)破解使用正常
> 
> 應該是你沒有git pull更新同步新版破解吧？

是的，多谢提醒。
