### ISSUE TITLE
Surge 5.4.1 注入后有问题 详见图片

### ISSUE THREAD

**Issue by xzygreen** [QiuChenlyOpenSource/InjectLib#126]
surge：5.4.1
macos：14.1

这是一个FAT格式二进制,携带 2 个架构的代码(Intel/Apple Silicon ARM64)

发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
添加 LC_LOAD_DYLIB 指令到通用架构, 应用程序：/Applications/Surge.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag。
Need Deep Sign.
开始签名...
准备自动计算Helper偏移参数...
2023-11-12 09:49:03.433 SearchParttenCode[6797:226888] 当前CPU类型是 arm64
2023-11-12 09:49:03.433 SearchParttenCode[6797:226888] ==== 得到了 /Applications/Surge.app/Contents/Library/LaunchServices/com.nssurge.surge-mac.helper
2023-11-12 09:49:03.433 SearchParttenCode[6797:226888] ==== nfat_arch = 2 = 33554432
2023-11-12 09:49:03.472 SearchParttenCode[6797:226888] ==== 没有匹配到数据
2023-11-12 09:49:03.473 SearchParttenCode[6797:226888] 成功更新了目标文件中的内容.
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.
No matching processes were found
rm: /Library/LaunchDaemons/com.nssurge.surge-mac.helper.plist: No such file or directory
rm: /Library/PrivilegedHelperTools/com.nssurge.surge-mac.helper: No such file or directory
感谢QQ 302****398 用户无偿提供授权信息。
大胆！检测到你在用盗版软件，这可能会危害你的设备！还可能会导致你被有关监管部门或工业和信息化委员会上门约谈，请慎重考虑是否决定使用盗版！
正在定位你的Mac物理地址...GPS定位中...你跑不掉了! 即将联系Surge开发者发送你的Mac所有信息，你即将被留存侵权数字证据，束手就擒！
定位你的Mac物理地址完成，正在向国家安全局特工发送你的逮捕许可...
起始点在 0,文件已被修改，跳过注入Helper。
下发逮捕许可完成,即将有人来查你的水表，你别急...海内存知己,天涯若比邻.正在黑进你的Mac,目前已成功骗取到用户root密码.
/Applications/Surge.app/Contents/Library/LaunchServices/com.nssurge.surge-mac.helper: replacing existing signature
/Applications/Surge.app/Contents/Library/LaunchServices/com.nssurge.surge-mac.helper: main executable failed strict validation
/Applications/Surge.app: replacing existing signature
恭喜你！你的Mac已经被我植入了后门程序,现在即将结束整个进程，特工已经在对面楼中布下天罗地网，请主动自首争取宽大处理(虽然宽大不了几天)，记得下辈子不要用盗版软件🙏。

App处理完成

<img width="242" alt="截屏2023-11-12 09 48 14" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/125412114/137d0b5e-5414-4cbf-b5fc-9b2ee9b510ca">
<img width="242" alt="截屏2023-11-12 09 48 25" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/125412114/73e6d9fa-58a7-4597-9787-666a19a229a7">
<img width="431" alt="截屏2023-11-12 09 48 44" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/125412114/0a043d43-14cc-4459-ac8b-69210ef94b52">

**Comment by QiuChenly** [comment]
5。4.1要用最新的Beta版本 2475，如果还有这个问题就是你的问题。
