### ISSUE TITLE
[祈愿] 希望大佬能下次更新捎带破解下这个app-ServerCat

### ISSUE THREAD

**Issue by Smecta** [QiuChenlyOpenSource/InjectLib#133]
官网：https://servercat.app/
苹果商店地址：https://apps.apple.com/cn/app/servercat-ssh-%E7%BB%88%E7%AB%AF-linux-%E7%9B%91%E6%8E%A7/id1501532023
app 截图
<img width="144" alt="CleanShot 2023-11-15 at 15 06 57@2x" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/30615458/2d03b1d9-80cb-4008-a4cf-b39ec24406e0">
<img width="1025" alt="CleanShot 2023-11-15 at 15 07 06@2x" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/30615458/c95faadd-12fc-46aa-8092-bbff79009383">

**Comment by QiuChenly** [comment]
不好意思哈 基本不太可能
