### ISSUE TITLE
MAS 版 Office 365 更新后许可证无效

### ISSUE THREAD

**Issue by Leowolf93** [QiuChenlyOpenSource/InjectLib#134]
硬件：M1 Pro MacBook Pro
系统版本：14.1.1 (23B81)
Office(Word/Excel/PPT/Outlook): 16.79
InjectLib版本：最新，已通过Github Desktop拉取最新的版本。
辅助信息：
在App Store更新并重新注入后，依旧提示未激活。
<img width="945" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/115647782/a023620a-613e-4c02-8d67-ec780497fd68">
<img width="406" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/115647782/210538b7-2171-4274-aa29-2df2cded996a">
十分感谢。

**Comment by xzygreen** [comment]
只能用macApp Store上的订阅版

**Comment by Leowolf93** [comment]
> 只能用macApp Store上的订阅版
我的就是在Mac App Store 下载的 Office 订阅版。

**Comment by Leowolf93** [comment]
> 只能用macApp Store上的订阅版


我的就是在Mac App Store 下载的 Office 订阅版。

**Comment by QiuChenly** [comment]
已修复
