### ISSUE TITLE
ProxyMan 4.14.0 破解后，手动重载功能失效。

### ISSUE THREAD

**Issue by uclort** [QiuChenlyOpenSource/InjectLib#135]
![Xnip2023-11-16_10-28-27](https://github.com/QiuChenlyOpenSource/InjectLib/assets/17818831/6dc9151e-6bf8-45b5-b4cf-1eb964dcee70)

brew 安装 proxyman 4.14.0 版本， 打开安装代理工具尝试抓包，正常。
因为使用的外部代理模式，关闭了开启自动覆盖代理功能，打开了关闭恢复代理功能。
关闭 app 后执行原神破解，破解完再次打开，手动点击重载功能失效，菜单栏开启也无效。

**Comment by QiuChenly** [comment]
事实上我测试过了是正常的。
这个问题只会出现在Helper错误上。我建议你卸载Helper重装。

**Comment by uclort** [comment]
OS Ventura 13.5.2

反复重新安装了多次，ProxyMan 也重新安装了多次，安装完 helper 之后，直接 cmd+q 退出，再打开，偏好设置里是未安装状态，安装按钮不可点击，只能去 /Library/PrivilegedHelperTools/com.proxyman.NSProxy.HelperTool 手动删除再次打开安装，安装完还是一样的情况。

**Comment by QiuChenly** [comment]
那你这个很奇怪啊 我这里倒是没遇到问题呢
