### ISSUE TITLE
emby server 按破解说明替换dll文件后无法访问

### ISSUE THREAD

**Issue by zhychen1173** [QiuChenlyOpenSource/InjectLib#137]
按破解说明中的链接 https://github.com/MediaBrowser/Emby.Releases/releases/download/4.7.14.0/embyserver-osx-x64-4.7.14.0.zip 下载了指定的 Emby server版本并安装。

安装之后，本机 localhost:8096 可以正常访问，并可进行相关配置。
之后退出emby server，将破解文件替换，再重新运行。这时再访问 http://localhost:8096/web/index.html  就报
<img width="744" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/117578752/86001b32-9f98-423f-b8d0-eaab571e88da">

打开 configure emby 和 emby premiere 都是报同样的错误。

请教大神如何解决？谢谢。

**Comment by zhychen1173** [comment]
发现我直接右键另存为的两个破解文件，居然文件大小不对，跟下载的整个原神破解包中的文件大小不一致，应该是这个问题造成的，汗。。。

**Comment by zhychen1173** [comment]
用整个破解包里的破解文件重新替换后，premiere 页面还是这样的，没有显示js文件中的超级会员、永不失效信息，不知是否正常？
![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/117578752/f690b193-bfe7-4845-af8e-35e5b3e231a8)

**Comment by QiuChenly** [comment]
清除浏览器缓存。
