### ISSUE TITLE
MWeb Pro 4.5.1 使用注入方式启动，并选择库所在目录后无法使用

### ISSUE THREAD

**Issue by nmweizi** [QiuChenlyOpenSource/InjectLib#139]
- MWeb Pro 4.5.1 使用注入库方式启动，并选择现有文档库所在目录后，无法使用。
- intel 
- 出现这个情况是下面的情形：
   1. MWeb Pro 4.5.1 正常使用
   2. 重启电脑
   3. MWeb Pro启动后报错，重新安装MWeb Pro，注入，签名
   4. 启动后出现选择现有文档库所在目录，选择已有的原文档的目录，提示存储位置已有文档，点击开始使用不能进入主界面。
- 使用Surge的MitM拦截並激活部分方式，功能正常没问题

<img width="627" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/1232444/f88b9303-c84b-4a56-9679-e8726c9e849b">

**Comment by nmweizi** [comment]
是不是啥文件权限不对

**Comment by QiuChenly** [comment]
我这里正常使用 你看看是不是App自己的BUg
