### ISSUE TITLE
Lightroom Classic 12.4

### ISSUE THREAD

**Issue by digitalhouse** [QiuChenlyOpenSource/InjectLib#14]
Lightroom Classic 12.4 arm版有機會支持嗎?
如果有需要檔案我可以協助提供

**Comment by QiuChenly** [comment]
already  fix it.check and reporting.

**Comment by digitalhouse** [comment]
> already fix it.check and reporting.

經過測試，軟體可以打開，但編輯照片功能全部反灰不能調整

**Comment by digitalhouse** [comment]
已在其他地方找到破解，並可正常使用
