### ISSUE TITLE
关于InjectLib项目的一点想法

### ISSUE THREAD

**Issue by nmweizi** [QiuChenlyOpenSource/InjectLib#141]
## 关于InjectLib项目的一点想法

现在这个项目参与门槛很高，只有秋大佬这样精通macos程序编写及破解知识才能够修改。如果将破解部分描述成json文件，用libInjectLib.dylib读取这个文件并注入，就能够简化成一次编译，仅修改json配置文件，即可实现相应的功能，类似项目中的SearchParttenCode和Patch.json思路。就像win下的很多工具PYG内存破解补丁、樱花补丁制作工具、KeyMake等工具一样。macos下好像还没这么好的工具。
这样，可以让我这样不会编写apply下程序的小白，也能参与项目。简化难度后，参与的人越来越多，破解的软件会更加丰富。
同frida比较，编写难度低，内存占用小，可用于生产。
一点想法，高手们看了也许不值一提:blush:。

比如：

```json
[
  {
    "applicationName": "xxx",
    "ver": "1.1.1",
    "hookPtrByMatchMachineCode": {
      0,
      "aa bb dd",
      "bb cc dd",
      1,
      1
    },
    "hookOCMethod": {
      "main",
      "init",
      0
    },
    "hookOCMethod": {
      0x10000,
      0
    },
  },
]
```

**Comment by CodeGather** [comment]
这个项目不适合小白用户玩的，哈哈，大神开了培训班呀

**Comment by Ran-Xing** [comment]
> 这个项目不适合小白用户玩的，哈哈，大神开了培训班呀

我要报名拖地保洁 @CodeGather

**Comment by QiuChenly** [comment]
你说的对，但是InjectLib是一个完全免费不加密的代码注入框架，故事发生在一个名为Github的世界上，你需要扮演一个叫做Contribute的角色，提交Commit或issues来帮助项目变得更强，最后，逐步发掘--InjectLib底层技术的真相。
