### ISSUE TITLE
surge注入后启动闪退

### ISSUE THREAD

**Issue by HypocriteYe** [QiuChenlyOpenSource/InjectLib#151]
macOS 11.7.5 (20G1225)
surge 5.4.3 (2534)
用的surge.sh纯净安装的，安装之前已经用App Cleaner卸干净了
![iShot_2023-12-07_11 43 00](https://github.com/QiuChenlyOpenSource/InjectLib/assets/85000263/cc4a7871-0a52-4e40-870e-b52e696ea7cf)

![iShot_2023-12-07_11 47 55](https://github.com/QiuChenlyOpenSource/InjectLib/assets/85000263/b230f1c2-1e0f-4af6-a6d3-88d99c9f8bfd)

**Comment by HypocriteYe** [comment]
使用（2538），执行完surge.sh，还是闪退
![iShot_2023-12-07_11 52 55](https://github.com/QiuChenlyOpenSource/InjectLib/assets/85000263/73af4471-86b4-4033-b67d-d0d5fbdaf73b)

**Comment by wolffya** [comment]
为什么不原神启动呢

**Comment by HypocriteYe** [comment]
> 为什么不原神启动呢

执行command之后打开还是闪退

**Comment by kcgithub2014** [comment]
卸载后重启再走流程
