### ISSUE TITLE
Xnip 2.2.3 注入后程序无响应

### ISSUE THREAD

**Issue by TryA9ain** [QiuChenlyOpenSource/InjectLib#156]
系统环境：

```
Apple M2
16 GB 内存
macos Ventura 13.2.1
```

![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/51145610/27411e5d-4563-48a3-8048-1c144be7b9b2)

在 App store 下载 Xnip（版本 2.2.3）

![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/51145610/509f4a86-688c-4260-b612-8567e61215f0)

下载安装完毕后，配置好 Xnip 截图需要的权限，退出 Xnip。

![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/51145610/d3ef0b12-6c67-4962-93c8-baffb9ad2498)

运行 "原神_启动"。

![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/51145610/ed7e915f-90e1-461c-904b-06b57fda79e3)

```
[🤔] [Xnip] - [2.2.3] - [com.zzd.Xnip]是受支持的版本，是否需要注入？y/n(默认n)
y
开始注入App: com.zzd.Xnip


====================
2023.2.26 秋城落叶修改版
感谢insert_dylib的开源人员！仓库地址：https://github.com/Tyilo/insert_dylib
====================

/Applications/Xnip.app/Contents/Frameworks/DKDrawKit.framework/Versions/A/DKDrawKit 目标文件已经存在. 要重写他吗? [y/n] y
这是一个FAT格式二进制,携带 2 个架构的代码(Intel/Apple Silicon ARM64).
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
添加 LC_LOAD_DYLIB 指令到通用架构, 应用程序：/Applications/Xnip.app/Contents/Frameworks/DKDrawKit.framework/Versions/A/DKDrawKit。
开始签名...
/Applications/Xnip.app: replacing existing signature
App处理完成。

```

![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/51145610/9318bc22-2c36-4fc8-9be7-f5882f423adf)

启动 Xnip 程序无响应。

![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/51145610/3009300d-a286-4924-9540-9618ec88f89c)

**Comment by QiuChenly** [comment]
这都几年前的老软件了，没必要用，你换别的试试先。这软件我弄了玩的 说实话我自己都不用。

**Comment by X1a0He** [comment]
该问题已解决

**Comment by TryA9ain** [comment]
> 这都几年前的老软件了，没必要用，你换别的试试先。这软件我弄了玩的 说实话我自己都不用。

CleanShot X 用这个多一些嘛？
