### ISSUE TITLE
Ulysses没包含在内的原因？

### ISSUE THREAD

**Issue by wangzhehyd** [QiuChenlyOpenSource/InjectLib#157]
看到InjectPluginCode里面对Ulysses是支持的，编译InlineInjectPlugin注入在关闭SIP的情况下可用。
测试用软件版本 33.1 (76319)，运行平台MacBook M2 ，操作系统14.2。
开启SIP不行，对注入文件单独签名以及对整个app的deep签名都不行，具体过程如下截图：
![1702553898400](https://github.com/QiuChenlyOpenSource/InjectLib/assets/6177304/ebf7101f-c0ec-4430-a008-3c86187e4e09)

这个仓库里面基本都支持SIP开启下运行，Ulysses目前是确实无法支持？

**Comment by QiuChenly** [comment]
不是 没那么复杂 单纯就是我根本不用UIysses。

**Comment by wangzhehyd** [comment]
> 不是 没那么复杂 单纯就是我根本不用UIysses。

所以不是技术问题，如果要SIP开启下用，可以往什么方向尝试？像Navicat Preuime 16.3.4那样找没有签名验证的文件注入也不是个解决问的法子。

**Comment by ClassmateShen** [comment]
> > 不是 没那么复杂 单纯就是我根本不用UIysses。
> 
> 所以不是技术问题，如果要SIP开启下用，可以往什么方向尝试？像Navicat Preuime 16.3.4那样找没有签名验证的文件注入也不是个解决问的法子。

是这样的，如果你要在开启SIP的情况下使用，你需要处理掉iCloud，原因如下：
1.要想开SIP使用，必须要签名
2.而必须要有效的签名才能有访问iCloud的权限
3.如果你的签名不支持iCloud，并且不处理原程序中的iCloud，则将会引起崩溃

因此你如果要开启SIP使用，必须要处理iCloud，关闭SIP使用是因为关闭SIP后系统将不再对签名进行校验，即更改完程序无需重新签名即可使用

**Comment by wangzhehyd** [comment]
> > > 不是 没那么复杂 单纯就是我根本不用UIysses。
> > 
> > 
> > 所以不是技术问题，如果要SIP开启下用，可以往什么方向尝试？像Navicat Preuime 16.3.4那样找没有签名验证的文件注入也不是个解决问的法子。
> 
> 是这样的，如果你要在开启SIP的情况下使用，你需要处理掉iCloud，原因如下： 1.要想开SIP使用，必须要签名 2.而必须要有效的签名才能有访问iCloud的权限 3.如果你的签名不支持iCloud，并且不处理原程序中的iCloud，则将会引起崩溃
> 
> 因此你如果要开启SIP使用，必须要处理iCloud，关闭SIP使用是因为关闭SIP后系统将不再对签名进行校验，即更改完程序无需重新签名即可使用

那没有有效签名的情况下想开启SIP用岂不是无解，还属于技术问题，哈哈哈。

**Comment by ClassmateShen** [comment]
> > > > 不是 没那么复杂 单纯就是我根本不用UIysses。
> > > 
> > > 
> > > 所以不是技术问题，如果要SIP开启下用，可以往什么方向尝试？像Navicat Preuime 16.3.4那样找没有签名验证的文件注入也不是个解决问的法子。
> > 
> > 
> > 是这样的，如果你要在开启SIP的情况下使用，你需要处理掉iCloud，原因如下： 1.要想开SIP使用，必须要签名 2.而必须要有效的签名才能有访问iCloud的权限 3.如果你的签名不支持iCloud，并且不处理原程序中的iCloud，则将会引起崩溃
> > 因此你如果要开启SIP使用，必须要处理iCloud，关闭SIP使用是因为关闭SIP后系统将不再对签名进行校验，即更改完程序无需重新签名即可使用
> 
> 那没有有效签名的情况下想开启SIP用岂不是无解，还属于技术问题，哈哈哈。

有解啊，我不是说了，处理掉iCloud，不让程序调用iCloud就好了

**Comment by wangzhehyd** [comment]
> > > > > 不是 没那么复杂 单纯就是我根本不用UIysses。
> > > > 
> > > > 
> > > > 所以不是技术问题，如果要SIP开启下用，可以往什么方向尝试？像Navicat Preuime 16.3.4那样找没有签名验证的文件注入也不是个解决问的法子。
> > > 
> > > 
> > > 是这样的，如果你要在开启SIP的情况下使用，你需要处理掉iCloud，原因如下： 1.要想开SIP使用，必须要签名 2.而必须要有效的签名才能有访问iCloud的权限 3.如果你的签名不支持iCloud，并且不处理原程序中的iCloud，则将会引起崩溃
> > > 因此你如果要开启SIP使用，必须要处理iCloud，关闭SIP使用是因为关闭SIP后系统将不再对签名进行校验，即更改完程序无需重新签名即可使用
> > 
> > 
> > 那没有有效签名的情况下想开启SIP用岂不是无解，还属于技术问题，哈哈哈。
> 
> 有解啊，我不是说了，处理掉iCloud，不让程序调用iCloud就好了

用这玩意不就是图他能iCloud上存储，去掉就没必要玩了

**Comment by ClassmateShen** [comment]
> > > > > > 不是 没那么复杂 单纯就是我根本不用UIysses。
> > > > > 
> > > > > 
> > > > > 所以不是技术问题，如果要SIP开启下用，可以往什么方向尝试？像Navicat Preuime 16.3.4那样找没有签名验证的文件注入也不是个解决问的法子。
> > > > 
> > > > 
> > > > 是这样的，如果你要在开启SIP的情况下使用，你需要处理掉iCloud，原因如下： 1.要想开SIP使用，必须要签名 2.而必须要有效的签名才能有访问iCloud的权限 3.如果你的签名不支持iCloud，并且不处理原程序中的iCloud，则将会引起崩溃
> > > > 因此你如果要开启SIP使用，必须要处理iCloud，关闭SIP使用是因为关闭SIP后系统将不再对签名进行校验，即更改完程序无需重新签名即可使用
> > > 
> > > 
> > > 那没有有效签名的情况下想开启SIP用岂不是无解，还属于技术问题，哈哈哈。
> > 
> > 
> > 有解啊，我不是说了，处理掉iCloud，不让程序调用iCloud就好了
> 
> 用这玩意不就是图他能iCloud上存储，去掉就没必要玩了

那如果是这样的话除了关SIP，其他无解
