### ISSUE TITLE
Feature：希望能支持Lattics

### ISSUE THREAD

**Issue by ttbug** [QiuChenlyOpenSource/InjectLib#161]
下载地址：https://lattics.zineapi.com/zh-CN
一款支持本地存储的知识管理工具，大佬看看有没有兴趣

**Comment by QiuChenly** [comment]
这是一个前端项目，将不会被纳入InjectShell中，仅供Hook脚本供高级用户手动asar解包替换破解使用。

**Comment by ttbug** [comment]
> 这是一个前端项目，将不会被纳入InjectShell中，仅供Hook脚本供高级用户手动asar解包替换破解使用。

好的，了解了，多谢
