### ISSUE TITLE
Navicat Premium 16 注入后程序无法打开

### ISSUE THREAD

**Issue by Lstink** [QiuChenlyOpenSource/InjectLib#168]
## 系统环境
* cpu: m1 pro
* 系统版本：14.2.1 (23C71)
* 软件版本：Navicat Premium 16 （16.3.4）
## 操作步骤
1. 从 `appstore`下载 `Navicat Premium 16`
<img width="1265" alt="iShot_2023-12-24_22 25 24" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/38460927/32b80700-ae76-4eb9-85a2-eeeb1354547c">
2. 打开一次 `Navicat Premium 16` 然后关闭，接着双击打开 `原神_启动.command`
<img width="846" alt="iShot_2023-12-24_22 30 08" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/38460927/f10f5b65-cb4d-483e-b262-1ca44cbaa511">
3. 根据提示，开始注入
<img width="845" alt="iShot_2023-12-24_22 29 13" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/38460927/4c828710-6bec-4b2b-a073-3e33940f89bb">
4. 尝试运行 `Navicat Premium 16`
<img width="1036" alt="iShot_2023-12-24_22 32 36" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/38460927/a594c90f-6b03-43c6-bfcf-fbecd35321dc">
此时已经无法打开，重启也是同样的问题，尝试过多次卸载，使用 `App Cleaner` 清理，然后继续安装注入仍然是同样的结果。

**Comment by QiuChenly** [comment]
这个我还没更新/

**Comment by just-tktok** [comment]
我也遇到这个问题，系统版本是13.6.3

**Comment by QiuChenly** [comment]
我知道，等更新即可。只是没发布而已。

**Comment by wdkGitHub** [comment]
感觉 datagrip 比这个好用

**Comment by QiuChenly** [comment]
已解决。

**Comment by duanyongcheng77** [comment]
@Lstink 请问，你更新代码后好了吗？我也是m1 pro更新后没有还是意外退出。

**Comment by Lstink** [comment]
好了，如果你是pull代码，更新之后记得切换分支，分支变了，原来的分支删了。然后再卸载删除干净重新注入就好了

**Comment by Lstink** [comment]
> @Lstink 请问，你更新代码后好了吗？我也是m1 pro更新后没有还是意外退出。

@duanyongcheng77 好了，如果你是pull代码，更新之后记得切换分支，分支变了，原来的分支删了。然后再卸载删除干净重新注入就好了

**Comment by duanyongcheng77** [comment]
@Lstink  好的，应该是我没有删除干净。感谢

**Comment by duanyongcheng77** [comment]
@Lstink  老哥，我注入以后连接不能保存密码了。你有遇到吗？

**Comment by Lstink** [comment]
> @Lstink 老哥，我注入以后连接不能保存密码了。你有遇到吗？

@duanyongcheng77 我昨天在 M1 上正常，然后我今天在公司的 intel cpu上注入之后也是不能保存密码

**Comment by just-tktok** [comment]
我的m2，也保存不了密码
