### ISSUE TITLE
Navicat破解后无法记住数据库密码

### ISSUE THREAD

**Issue by Leowolf93** [QiuChenlyOpenSource/InjectLib#171]
使用的InjectLib 版本：最新版本
使用的分支：Release-2023
Navicat 版本：App Store 下载的 16.3.4
系统版本：macOS Sonoma 14.2.1
芯片：Apple M1 Pro 

已经给了终端 App 管理、开发者工具权限
已经在注入之前打开过一次Navicat

在注入后打开，发现已经激活，但是不能保存密码，在保存密码的时候弹窗。

![CleanShot 2024-01-03 at 10 33 17@2x](https://github.com/QiuChenlyOpenSource/InjectLib/assets/115647782/26299aea-cba6-42d3-87c9-9eef38b41082)

谢谢。

**Comment by QiuChenly** [comment]
应该是签名权限问题，可能还是文件访问权限的bug。有空我会修的。

**Comment by Leowolf93** [comment]
> 应该是签名权限问题，可能还是文件访问权限的bug。有空我会修的。 临时解决办法是不签名原始App，也就是关闭SIP用。

谢谢大佬，辛苦了
