### ISSUE TITLE
Proxyman 最新版本 4.16 破解失败，4.15 破解成功。

### ISSUE THREAD

**Issue by uclort** [QiuChenlyOpenSource/InjectLib#173]
4.16 版本运行完原神后打开 Proxyman 还是免费版，使用卸载工具完全卸载 Proxyman 后重装再次运行原神还是免费版。

下载 Proxyman 4.15 版本后运行原神，破解成功。

https://proxyman.io/changelog

macOS 13.5.2

**Comment by QiuChenly** [comment]
已修复。
