### ISSUE TITLE
cleanMyMac X 4.14.6注入后提示意外退出

### ISSUE THREAD

**Issue by SNN1** [QiuChenlyOpenSource/InjectLib#176]
M3 pro 的mac，系统版本：Sonoma 14.2.1
1、在此链接下载的压缩包，解压后安装，安装完成后关闭，开始注入：
![4561705481946_ pic](https://github.com/QiuChenlyOpenSource/InjectLib/assets/41176222/261920d3-427e-4621-a4bb-020d24309b61)
2、破解步骤：
![4581705482015_ pic](https://github.com/QiuChenlyOpenSource/InjectLib/assets/41176222/a72ca3fe-a219-4b86-871d-5394ccc8e56e)
![4591705482028_ pic](https://github.com/QiuChenlyOpenSource/InjectLib/assets/41176222/ad3021d8-654f-4aff-8300-de8747c1f785)
3、打开报错：
![4571705481952_ pic](https://github.com/QiuChenlyOpenSource/InjectLib/assets/41176222/9bdc269b-347f-4c7b-85d8-2ee96360b326)

**Comment by QiuChenly** [comment]
仔细看，我发的是两个版本，你应该直接下载我提供下载链接的SetApp版本地址，而不是官方版本。
