### ISSUE TITLE
激活Bug

### ISSUE THREAD

**Issue by Nuoyancv** [QiuChenlyOpenSource/InjectLib#182]
ulyess,mindmac,devutil 激活后每次打开都会提示，qiuchengly Team 开源版本举报的提示框，设备：mac 2021 M1pro。使用目前最新的[InjectLib]，时间20240122

**Comment by Nuoyancv** [comment]
<img width="278" alt="iShot_2024-01-22_11 38 26" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/96186037/fdf81a73-dbe7-43a3-afb9-5cde00276d35">

**Comment by QiuChenly** [comment]
好像是一个弹框错误，稍后重新编译提交。

**Comment by QiuChenly** [comment]
已解决。
