### ISSUE TITLE
MacOS 14.3 注入后所有app都不能打开

### ISSUE THREAD

**Issue by 9d84** [QiuChenlyOpenSource/InjectLib#187]
## 基本信息
- 芯片: Apple M2
- 系统: MacOS 14.3
- SIP 和 SSV 均已关闭
- 脚本用的是 root 运行
- 脚本已切换至 ```dev-2024``` 分支( ```commit f33767dcbc94a87ed0cdb36bf002e679ad96a13d```)

## 错误信息
好像注入的app 都是 ```Termination Reason:    Namespace DYLD, Code 1 Library missing```
[ps.log](https://github.com/QiuChenlyOpenSource/InjectLib/files/14183420/ps.log)
[servercat.log](https://github.com/QiuChenlyOpenSource/InjectLib/files/14183425/servercat.log)

**Comment by QiuChenly** [comment]
/Applications/ServerCat.app/Contents/MacOS/libInjectLib.dylib报错显示这个文件不存在 你可以检查一下吗

**Comment by QiuChenly** [comment]
怀疑是你在运行脚本的时候没有给存储权限？

**Comment by 9d84** [comment]
<img width="1440" alt="截屏2024-02-07 13 11 19" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/136144070/45612ddd-05f7-4775-ad2a-6fac40e22dc2">

**Comment by 9d84** [comment]
改权限后好了，建议脚本加一个改权限的功能。

**Comment by QiuChenly** [comment]
> 改权限后好了，建议脚本加一个改权限的功能。

细说
