### ISSUE TITLE
Parallels Desktop 出现错误

### ISSUE THREAD

**Issue by bearjing2005** [QiuChenlyOpenSource/InjectLib#19]
<img width="592" alt="截屏2023-06-19 10 35 38" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/38486144/e54b0eba-1871-4855-8bbf-ce358674ef99">
今日打开Parallels Desktop的时候提示错误，查看系统变成了未破解版

**Comment by QiuChenly** [comment]
该问题是补丁代码中一处判断出现操作错误，已修复并上传，请重新下载更新。
