### ISSUE TITLE
提问：软件安装并破解之后，是否可以打开 SIP?

### ISSUE THREAD

**Issue by xiaotianxt** [QiuChenlyOpenSource/InjectLib#2]

**Comment by QiuChenly** [comment]
这个问题你应该问macOS，如果和操作系统玩文字游戏可以让你feel better，i am ok.

**Comment by xiaotianxt** [comment]
> 这个问题你应该问macOS，如果和操作系统玩文字游戏可以让你feel better，i am ok.
> 
> 
> 
> Dinner问题直接关了，你为什么不想想执行个Shell需要关SIP？！

对不起，我不太理解你的意思。和操作系统玩文字游戏是啥意思？Dinner 问题又是啥意思呀？

执行 Shell 关闭 SIP 我的理解就是为了修改某些保护中的文件，以便修改破解。至于重新打开之后文件会保持“被修改”的状态，还是会让破解失效，我不太清楚，所以在 issue 里面请教你一下。

我昨天晚上用你的脚本破解了 parallels，然后把 SIP 重新打开了，破解状态依旧在。

**Comment by QiuChenly** [comment]
不会起作用。因为执行shell只是把文件修改了，而这里不会去修改系统文件，也用不到关闭sip，他只是为了把我的文件复制到.app中。

我之所以说玩文字游戏是因为在macOS中是不允许Dylib注入修改app内存的，你之所以打开SIP还是激活是因为我执行了关闭系统的注入检查，它会引起此app时而能运行时而不能运行的bug.

**Comment by xiaotianxt** [comment]
> 不会起作用。因为执行shell只是把文件修改了，而这里不会去修改系统文件，也用不到关闭sip，他只是为了把我的文件复制到.app中。
> 
> 
> 
> 我之所以说玩文字游戏是因为在macOS中是不允许Dylib注入修改app内存的，你之所以打开SIP还是激活是因为我执行了关闭系统的注入检查，它会引起此app时而能运行时而不能运行的bug.
> 
> 
> 
> 只有关闭系统保护我才能让我的代码在app中畅通无阻。

明白了，我决定还是打开 SIP，需要破解的时候麻烦点关掉😂

**Comment by QiuChenly** [comment]
错误的结论，想用破解只能关闭SIP。因为除了有些App不检查完整性以外很多App都会有系统检查文件是否被修改，你这么做是完全运行不了。至于你重新打开SIP还能运行，我需要得到更多的信息

**Comment by xiaotianxt** [comment]
> 错误的结论，想用破解只能关闭SIP。因为除了有些App不检查完整性以外很多App都会有系统检查文件是否被修改，你这么做是完全运行不了。至于你重新打开SIP还能运行，我需要得到更多的信息

学习了，我用 parallels 的机会不多，硬盘里面还是有重要文件不敢妥协。我昨天重新打开 SIP 之后，用了一会儿 parallels 没问题，或许下次打开就寄了🤣

**Comment by QiuChenly** [comment]
<img width="1112" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/24793281/c1bf237b-d25f-4891-956d-879d24d12c28">
在我这里，关闭SIP会无法通过系统的文件完整性检查。

**Comment by xiaotianxt** [comment]
> <img alt="image" width="1112" src="https://user-images.githubusercontent.com/24793281/245035655-c1bf237b-d25f-4891-956d-879d24d12c28.png"> 在我这里，关闭SIP会无法通过系统的文件完整性检查。

我好像也遇到了这个问题，但是已经创建的 Windows 虚拟机没受到影响，晚上熬夜脑子已经不太清醒了。

**Comment by QiuChenly** [comment]
如果过度关注SIP，那么Windows反而成了世界上最不安全的系统，因为windows只需要放一个dll文件到安装目录。程序就会主动加载所有的dll且不会检查是否合法，系统文件也可以通过高级管理员权限强制删除-----而macos即使关闭SIP也没法操作任何系统级文件。
