### ISSUE TITLE
acrobat pro 2023.003.20201 pro 功能无法用

### ISSUE THREAD

**Issue by guocity** [QiuChenlyOpenSource/InjectLib#20]
提示trial expired，所有pro 功能不能用，变成了reader
给点提示，修改什么，我自己来弄吧？

**Comment by QiuChenly** [comment]
可以自行用ida查看我的dylib文件 可以直接看到源代码 没有做混淆和加密

**Comment by guocity** [comment]
你可不可以更新一下你的库 https://github.com/QiuChenlyOpenSource/macOS-InjectPluginCode
这个比较好看一点

**Comment by etrahretep** [comment]
Please update for  2023.003.20215

**Comment by QiuChenly** [comment]
already update latest Acrobat Pro
