### ISSUE TITLE
macOS 14 SIP錯誤

### ISSUE THREAD

**Issue by digitalhouse** [QiuChenlyOpenSource/InjectLib#22]
macOS 14 beta2 確實已經關閉 SIP
執行報錯
<img width="920" alt="截圖 2023-06-22 14 03 55" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/786348/7d82dfbd-bb97-4b90-82c1-63c9e151e7f6">

**Comment by LoveJessyChen** [comment]
语句 这个 unless ret.include?("status: enabled") 中的unless改为if

**Comment by digitalhouse** [comment]
> 語句 這個 unless ret.include?("status: enabled") 中的unless改為if

已成功執行 另外PS 24.6昨天似乎又有更新了

LR 12.4 是不是沒希望了？

**Comment by LoveJessyChen** [comment]
LR Classic 12.4 可以用sice的U2B版本，群主目前 似乎还没准备更新Adobe的套件

**Comment by digitalhouse** [comment]
> LR Classic 12.4 可以用sice的U2B版本，群主目前 似乎還沒準備更新Adobe的套件

mac的有發佈嗎？ 我一直找不到 哪裡可以找得到呢？
