### ISSUE TITLE
@All Pls Upload your's Adobe App Core File (Need the arm64 Mac App)

### ISSUE THREAD

**Issue by QiuChenly** [QiuChenlyOpenSource/InjectLib#23]
1. Adobe PS 24.6 latest edition  /Applications/Adobe Photoshop/Adobe Photoshop.app/Contents/MacOS/Adobe Photoshop 2023
2. Adobe PS 24.7 latest edition /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/MacOS/Adobe Photoshop 2023

BaiDuYun / LanzouYun / 123Yun first, because im in china mainland.

**Comment by odison** [comment]
链接: https://pan.baidu.com/s/1sA2T3RJCJpVPYIT6H-zwUA?pwd=ijaz 提取码: ijaz

**Comment by odison** [comment]
链接：https://pan.baidu.com/s/1tGBSzlni60_-jhUkOGqUbw?pwd=5f73 
提取码：5f73

**Comment by LoveJessyChen** [comment]
Ps 24.6 Release （U2B Installer）：
https://www.123pan.com/s/X5tA-zKKwh.html  提取码：Gap1
