### ISSUE TITLE
Affinity Photo 2/Designer 2/Publisher 2 全家桶    | 2.1.1 注入失效

### ISSUE THREAD

**Issue by fourcute** [QiuChenlyOpenSource/InjectLib#25]
先预祝楼主马到功成 😄

版本更新报告
Affinity Photo 2/Designer 2/Publisher 2 全家桶    | 2.1.1  注入失效

**Comment by QiuChenly** [comment]
Frameworks/liblibaffinity.dylib 上传此文件给我 我懒得下载了 整个App900MB太大了 需要m系列二进制才可以分析

**Comment by fourcute** [comment]
[liblibaffinity.dylib.zip](https://github.com/QiuChenlyOpenSource/InjectLib/files/11952769/liblibaffinity.dylib.zip)

**Comment by QiuChenly** [comment]
Resolved,pls download test & report.

**Comment by quxin5605** [comment]
下载最新版的，很遗憾还是激活失败，这我的Frameworks/liblibaffinity.dylib文件，请大佬查收，谢谢！
[liblibaffinity.zip](https://github.com/QiuChenlyOpenSource/InjectLib/files/12000182/liblibaffinity.zip)

**Comment by QiuChenly** [comment]
重新测试。

**Comment by quxin5605** [comment]
> 

M1已测试OK，成功注入，谢谢大神！幸苦幸苦
