### ISSUE TITLE
我是19岁小妹妹

### ISSUE THREAD

**Issue by MacroXie** [QiuChenlyOpenSource/InjectLib#38]
# 我同意喜欢你，但是你别玩原神！

**Comment by miyuanbo** [comment]
？？？

**Comment by yoeaki** [comment]
> # 我同意喜欢你，但是你别玩原神！

**你是锤子，不是妹子！！！！！！**

**Comment by QiuChenly** [comment]
不要男妹妹 quickly gun

**Comment by yoeaki** [comment]
> 不要男妹妹 quickly gun

现在发展是什么进度？可以回来更新没？

**Comment by QiuChenly** [comment]
不能 你们到底上没上过大学 这几天都在备考期末考 怎么约 啊 人家在复习 你告诉我怎么约

**Comment by MacroXie** [comment]
你给她一对一教学

**Comment by yoeaki** [comment]
> 不能 你们到底上没上过大学 这几天都在备考期末考 怎么约 啊 人家在复习 你告诉我怎么约

那你小妹妹谈得少，我当年谈的时候，考试前一晚还给她一起复习
