### ISSUE TITLE
iShot 2.3.4 破解不是很稳定

### ISSUE THREAD

**Issue by godzeo** [QiuChenlyOpenSource/InjectLib#4]
iShot 2.3.4 破解不是很稳定

在M1 上重启软件可以
inter上 破解失败，没效果

**Comment by QiuChenly** [comment]
我这里使用正常，你下的什么版本

**Comment by godzeo** [comment]
> 我这里使用正常，你下的什么版本

app store ishot  2.3.4

是不是这个问题，识别版本错误
<img width="871" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/64398024/c5d1ad0d-d6b8-4898-850c-bbf5b0e007a6">

**Comment by QiuChenly** [comment]
卸载重新下载
