### ISSUE TITLE
Adobe Premiere Pro 有官方M1支持了

### ISSUE THREAD

**Issue by muzian666** [QiuChenlyOpenSource/InjectLib#43]
虽然不想打扰作者谈恋爱，但是还是要提一嘴hh
详情请见：https://helpx.adobe.com/premiere-pro/kb/premiere-pro-for-apple-silicon.html

祝作者追妹子成功！

**Comment by digitalhouse** [comment]
> 你說的對但是我下不到，你可以上傳M版本的二進制給我分析。

請問需要上傳檔案的檔案位置是?

我從macOS資料夾裡找到的Adobe Premiere Pro 2023檔案只有148KB

**Comment by digitalhouse** [comment]
> 你說的對但是我下不到，你可以上傳M版本的二進制給我分析。

看看是不是這個

链接: https://pan.baidu.com/s/1-yMprS2-mFPAg72SLK9Wfg?pwd=iuqd 提取码: iuqd 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by muzian666** [comment]
盲猜可能不是？QwQ 这个二进制文件怎么弄啊

**Comment by QiuChenly** [comment]
if (checkSelfInject("com.adobe.PremierePro.23")) {
        //Adobe Premiere Pro 2023
        uint32_t Registration = getImageVMAddrSlideIndex("Registration");

如果没有特殊说明 那么一般是MacOS下的主程序文件即可，比如PS。但是Pr比较特殊，他的地址是Framwork下的Registration，请上传M版本的此文件给我

**Comment by digitalhouse** [comment]
> ```
> if (checkSelfInject("com.adobe.PremierePro.23")) {
>     //Adobe Premiere Pro 2023
>     uint32_t Registration = getImageVMAddrSlideIndex("Registration");
> ```
> 
> 如果沒有特殊說明 那麼一般是MacOS下的主程序檔案即可，比如PS。但是Pr比較特殊，他的地址是Framwork下的Registration，請上傳M版本的此檔案給我

链接: https://pan.baidu.com/s/1zWuFRYjcP88Af03OhAB0dw?pwd=pfje 提取码: pfje 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by muzian666** [comment]
我附一个Onedrive的吧 QwQ
这个是23.5的
https://4dckwx-my.sharepoint.com/:u:/g/personal/lqa_4dckwx_onmicrosoft_com/Ed2wabzg-hRErR0m-n0-IBsBk2-lobHiOfLkMTEkDgNdqQ?e=ID0kNA

**Comment by QiuChenly** [comment]
Resolved,pls download test & report.

**Comment by digitalhouse** [comment]
> Resolved,pls download test & report.

M1沒辦法使用
跳出視窗
<img width="912" alt="截圖 2023-07-08 10 36 35" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/786348/066abb08-10b1-4441-bb2d-91b74744547e">

**Comment by digitalhouse** [comment]
23.6又更新了
链接: https://pan.baidu.com/s/14wCFkjtHriWQ4iy2zMm1kg?pwd=x5nr 提取码: x5nr 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by digitalhouse** [comment]
PR的部分我也更新了
24.0.0.17 arm版
链接: https://pan.baidu.com/s/1jsiMVniF7aFWoJJAVzGK8Q?pwd=rs6v 提取码: rs6v 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by digitalhouse** [comment]
PR 24.0.0.18 ARM版
https://mega.nz/file/bI5X1SJY#KnZvn1dcma2a8vNnmr9iR72j7NW8VmuKOyrerQPDaTk

**Comment by QiuChenly** [comment]
此问题已解决。
