### ISSUE TITLE
有考虑狠狠地注入Paste - Clipboard Manager吗?

### ISSUE THREAD

**Issue by LanYunDev** [QiuChenlyOpenSource/InjectLib#44]
https://apps.apple.com/cn/app/paste-clipboard-manager/id967805235
<img width="783" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/95263282/38ad6b8f-4219-451a-945f-6990e58773ae">

**Comment by LanYunDev** [comment]
已经狠狠地注入了.已经可以玩啦~
小小缺陷:要转译才能跑,iCloud不能同步,

**Comment by QiuChenly** [comment]
这也是计划的一部分

**Comment by gentlechj** [comment]
已经4.0.2版本了 🥹

**Comment by QiuChenly** [comment]
那也是计划的一部分

**Comment by QiuChenly** [comment]
already support 4.0.2
