### ISSUE TITLE
璃月我的璃月赐我一个璃月吧求求你了mihoyo🥺我真的测你吗

### ISSUE THREAD

**Issue by etrahretep** [QiuChenlyOpenSource/InjectLib#46]
What is the meaning of this sentence in English?
Look like spam...

**Comment by miyuanbo** [comment]
It is just a joke. 
"璃月" is a virtual thing in a game called YuanShen. 
"测你吗" might mean the f-word, which indicates that the developer is anxious about the game.

**Comment by TheInterestingSoul** [comment]
`璃月` is a fictional game map in Genshin Impact.

------

Additionally, a literal translation of the `停更` (discoutinued) part of README.md would help. But my vocabulary is sick, I managed to do the first half.

(The owner of this repo just dropped support and updates two weeks ago, attempting to chase a 19-year-old Genshin player. But Genshin is [so infamous among non-player world in China](https://pandayoo.com/2020/10/02/why-does-genshin-impact-make-some-chinese-players-feel-so-angry/), and this incident quickly became a meme in Chinese developer community.)

Also see #24 .

> # Project Discoutinued
>
> Trying to chase a 19-year-old recently.
> therefore this repo is basically discoutinued right now, and updates are done only for my full-time work 💻
> and i wont consider catching up these app's new version (and crack them), just wait til i get her 🧑‍🤝‍🧑
> (used to hate genshin and other mihoyo works, but) damn, for 💗 the loved one 👧 let's get into genshin world 😡👊 never regret it, go for it!

**Comment by ElementBridge** [comment]
虽然之前是个整活，还挺有意思，但是不建议把issue当成评论区用。它会将该问题下所有的反馈都发邮件给参与了此回复的账户。包括我这条也是。所以这个还是建议解决问题用吧。😂

**Comment by TheInterestingSoul** [comment]
> 虽然之前是个整活，还挺有意思，但是不建议把issue当成评论区用。它会将该问题下所有的反馈都发邮件给参与了此回复的账户。包括我这条也是。所以这个还是建议解决问题用吧。😂

但是discussion和issue都会自动发邮件，必须手动关unsubscribe。所以至少在github平台内这个问题无解……只有另开qq群或者tg
