### ISSUE TITLE
Parallels Desktop 18.3.2 support?

### ISSUE THREAD

**Issue by meichengg** [QiuChenlyOpenSource/InjectLib#47]
Hi, i've tried your tool, it worked for 18.3.1, but no longer works on 18.3.2. Will this version be supported?

**Comment by QiuChenly** [comment]
coming soon.

**Comment by QiuChenly** [comment]
Resolved,pls download test & report.

**Comment by 51517960** [comment]
可以用+

**Comment by digitalhouse** [comment]
> Resolved,pls download test & report.

M1測試破解沒成功 右上會有購買按鈕 查看版本顯示試用期限

**Comment by miyuanbo** [comment]
我的也没有效果，18.3.2，M1 Max

**Comment by zcx992132258** [comment]
> Resolved,pls download test & report.

为什么还在修复 不谈恋爱了吗？

**Comment by QiuChenly** [comment]
pls re-try new patch file and report.

**Comment by digitalhouse** [comment]
> pls re-try new patch file and report.

works
