### ISSUE TITLE
PHSPBETA 24.7 失败了

### ISSUE THREAD

**Issue by guocity** [QiuChenlyOpenSource/InjectLib#48]
新电脑上
acrobat, illustrator, 成功
结果就PHSPBETA 24.7失败，关了试用PHSP也关闭

**Comment by QiuChenly** [comment]
测试版更新很频繁 大版本号24.7不变 所以无效了

**Comment by QiuChenly** [comment]
你可以上传一下你的ps 24.7最新测试版主程序PhotoShop文件让我分析一下

**Comment by digitalhouse** [comment]
> 你可以上傳一下你的ps 24.7最新測試版主程序PhotoShop檔案讓我分析一下

链接: https://pan.baidu.com/s/1egMKSBXdWq-ScMynrxAu1A?pwd=awvv 提取码: awvv 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by guocity** [comment]
我要等今晚，很奇怪的事，这个安装程序我装了自己的3次，都没问题，就昨天，换了台新电脑，所以我卸载了，也不可以，我用了旧版的injectlib 也不可以，一关了trial 就退出

**Comment by guocity** [comment]
看看这个可不可以
https://1drv.ms/f/s!AmWMEG6dxFTdgZ9pcJHMtO8SCn8a_g?e=pkdJpU

**Comment by digitalhouse** [comment]
已經看到24.7的破解了
也可以成功正常使用

**Comment by QiuChenly** [comment]
非Beta版本24.7.0 已重新上传

**Comment by digitalhouse** [comment]
我等等上傳一份最新arm版的PS 23.7跟PS 25 Beta上來吧

**Comment by digitalhouse** [comment]
已上傳
链接: https://pan.baidu.com/s/1AA4v93JKKq6TIz2FC7Oivw?pwd=bmg9 提取码: bmg9 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by QiuChenly** [comment]
> 已上傳 链接: https://pan.baidu.com/s/1AA4v93JKKq6TIz2FC7Oivw?pwd=bmg9 提取码: bmg9 复制这段内容后打开百度网盘手机App，操作更方便哦

感谢，他们的版本号是多少

**Comment by digitalhouse** [comment]
> > 已上傳 链接: https://pan.baidu.com/s/1AA4v93JKKq6TIz2FC7Oivw?pwd=bmg9 提取码: bmg9 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> @digitalhouse 有mega盘吗 我百度云会员过期了 298太贵了没续费 你传一个mega或者pixeldrain或者别的什么免费盘 我这里都可以不限速下载

上傳了
https://mega.nz/folder/3RIj2LBI#823ntUDH4G7EqGWaCq2d5w

**Comment by QiuChenly** [comment]
现在已经可以测试ARM64 版本的PS 24.7/25.0 Beta版本。

**Comment by digitalhouse** [comment]
> 現在已經可以測試ARM64 版本的PS 24.7/25.0 Beta版本。

Beta版幾乎天天在更新，明天進公司在上傳最新版的。

**Comment by digitalhouse** [comment]
測試24.7可以使用 就是打開頁面會有訂閱已結束的紅字。但可正常使用
25因為又更新了 所以不能使用 已重新上傳新版檔案
https://mega.nz/file/jVpySB7C#QmXiqZyeEOvfk1WAP-g1o9gjpSI1a9RapW0UNn4_8Xg

**Comment by QiuChenly** [comment]
注册一个没有试用过的账户就不会出现红色的订阅已经结束字样

**Comment by guocity** [comment]
25.0 破解后打开，Adobe Photoshop (Beta) quit unexpectedly.
对了，ida64 有没有破解版？

**Comment by digitalhouse** [comment]
> 25.0 破解後打開，Adobe Photoshop (Beta) quit unexpectedly. 對了，ida64 有沒有破解版？

ida64應該是別想了 本身就是逆向軟體 它都很清楚破解的手法 要有早就有了

**Comment by xianfei** [comment]
ps 25.0   20230817.m.2290  版本启动界面后闪退

**Comment by miosx** [comment]
<img width="944" alt="iShot" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/131627176/9b657983-64cc-44aa-a2cf-428b41f4a1eb">
完美，原神启动。

**Comment by QiuChenly** [comment]
已通杀，此帖终结。
