### ISSUE TITLE
Surge是不能用了？

### ISSUE THREAD

**Issue by miosx** [QiuChenlyOpenSource/InjectLib#49]
Surge是不能用了？
哪个版本能用呢？

**Comment by wdkGitHub** [comment]
大佬说吃里扒外的给举报了🤣，下载他给的下载地址可以用

**Comment by AQiui** [comment]
有没有下载链接

**Comment by dandan7675** [comment]
期待兄弟能抽空出手；这软件太贵，没法下手。拜谢

**Comment by kratos9394** [comment]
下载的打完补丁也用不了

**Comment by dandan7675** [comment]
5.20最后一个版本无法使用

**Comment by dandan7675** [comment]
<img width="492" alt="截屏2023-07-24 20 15 31" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/6188009/5567b4e0-01bc-469f-b1f3-1e47c28dabdf">

**Comment by wdkGitHub** [comment]
原来可以用的，发现也不能用了

**Comment by kratos9394** [comment]
<img width="495" alt="ass" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/57714345/af7a47b2-9248-4786-ae18-8e03d294581a">

**Comment by dandan7675** [comment]
用以前的5.1.1版本在M1上面可以启动,但无法启用系统代理和增强模式

<img width="867" alt="截屏2023-07-24 22 13 23" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/6188009/7849f3ba-79a6-4688-a572-493c7d645dee">

**Comment by wdkGitHub** [comment]
> <img alt="ass" width="495" src="https://user-images.githubusercontent.com/57714345/255615659-af7a47b2-9248-4786-ae18-8e03d294581a.png">

？？？ 办法破解吗？能否共享一下

**Comment by wdkGitHub** [comment]
<img width="473" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12813051/896df6d6-f6dd-4481-9840-3fe431c68c0f">
5.1.1 也不行

**Comment by wdkGitHub** [comment]
> <img width="495" alt="ass" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/57714345/af7a47b2-9248-4786-ae18-8e03d294581a">
> 
> 

@kratos9394 怎么激活的

**Comment by kratos9394** [comment]
驰为杂牌废铁，黑苹果完全没问题，就是用2303激活不了就尝试用2302，可以系统代理增强模式

**Comment by QiuChenly** [comment]
此贴终结。
