### ISSUE TITLE
Adobe Illustrator 27.5.0 已经是通用程序了

### ISSUE THREAD

**Issue by bearjing2005** [QiuChenlyOpenSource/InjectLib#5]
Adobe Illustrator 27.5.0 已经是通用程序了，是不是可以调整一下arm版的注入

**Comment by QiuChenly** [comment]
<img width="687" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/24793281/ae835815-9b42-4f6e-897f-52ff86fab6d3">
请提供ARM版本此文件 不同平台在adobe cc种只能下载本平台的产品

**Comment by bearjing2005** [comment]
不知道我现在的是不是已经是注入的。我用rosetta模式可以打开，关闭就不能打开
 Adobe Illustrator
<https://drive.google.com/file/d/19maotTcR_K_Tv12QRbmLvDQoTnxTWzF0/view?usp=drive_web>
[image: 截屏2023-06-13 17.41.33.png]

秋城落叶 ***@***.***> 于2023年6月13日周二 15:37写道：

**Comment by QiuChenly** [comment]
重新下载补丁测试

**Comment by bearjing2005** [comment]
测试了没有成功。今天更新了27.6.1，下面是文件链接。
阿里云 https://www.aliyundrive.com/s/vHP2FMmFvdd

**Comment by QiuChenly** [comment]
还没有提交针对27.6.1的更新，it is coming soon

**Comment by QiuChenly** [comment]
尝试解决，下载反馈。

**Comment by bearjing2005** [comment]
已更新测试，完美
