### ISSUE TITLE
如何加入qq群

### ISSUE THREAD

**Issue by dandan7675** [QiuChenlyOpenSource/InjectLib#51]
大神你好，想加入qq群，无奈看不懂入群的题目，请求加入组织

**Comment by MaxSecurity** [comment]
> 大神你好，想加入qq群，无奈看不懂入群的题目，请求加入组织
要不尝试一下百度?

**Comment by heygsc** [comment]
> 

无语了，谁不知道百度，这不是百度不出来吗

**Comment by heygsc** [comment]
> > 大神你好，想加入qq群，无奈看不懂入群的题目，请求加入组织
> > 要不尝试一下百度?

都知道百度啊，这不是不太好查么
