### ISSUE TITLE
致来围观看热闹的人

### ISSUE THREAD

**Issue by QiuChenly** [QiuChenlyOpenSource/InjectLib#56]
1. 不要乱提issues，都是高学历人才(这里特指排除大专及以下学历)不要搞的自己跟没文化的土狗一样什么事都参与。

    乱提issues的你有几个🐎可以4⃣️？非要到处留下类似于“到此一游”的标记才显得你格外不同？你觉得你在嘲笑谁呢？你这种行为也不过是哗众取宠的小丑罢了，我发现很多人认不清自己的定位。
  
    想留下标记可以去下面人多的那条issues回复，不要乱提新的issues影响老子心情。

2. 不是逆向破解爱好者不要加我群 乱加群你的🐎首先没一个 我不需要那么多的围观群众拉低我的群含金量
看热闹的人不要去加我的群，你要是也是软件安全兴趣爱好者我自然欢迎，不要整的什么b事都要参与一样非要加群。

    你觉得你加群能得到什么？里面全是高学历高素质(高素质这一点存疑)高智力人群，天天聊汇编话题你不觉得自己完全参与不了话题而感到自卑吗？我要是你就主动退群或者干脆不要加群，认清自己的实力。
    
    用ChatGPT生成答案都是错的，闲的没事的人不要去尝试，我一眼就能看出来是gpt给的答案。真要是爱好者加群就认真答题，就算错了我也会给过。
    
    加了群就发一句“慕名而来”、“围观”这种人，纯**杀软，你觉得你是什么身份？我需要你的“慕名”？我有什么”名“可以让你”幕“？
    
    简单来说，逆向爱好者可以加群，根本不懂软件安全或者完全就是凑热闹的乱加群，这种人先掂量一下你的🐎有几个。

**Comment by guocity** [comment]
来一个PSBETA 25.0
