### ISSUE TITLE
请问macOS 14 注入是否不支持呢？

### ISSUE THREAD

**Issue by fourcute** [QiuChenlyOpenSource/InjectLib#58]
_**版本号：14.0 Beta版(23A5301g)**_

**csrutil 状态**
mandyleigh@MacMiniWork InjectLib-main % csrutil status                     
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled
	BaseSystem Verification: disabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

_**注入成功：**_
mandyleigh@MacMiniWork InjectLib-main % clear

mandyleigh@MacMiniWork InjectLib-main % sudo /Users/mandyleigh/InjectLib-main/tool/insert_dylib /Users/mandyleigh/InjectLib-main/tool/libInjectLib.dylib /Applications/iShot.app/Contents/Frameworks/PTHotKey.framework/Versions/A/PTHotKey_副本 /Applications/iShot.app/Contents/Frameworks/PTHotKey.framework/Versions/A/PTHotKey

====================
2023.2.26 秋城落叶修改版
感谢insert_dylib的开源人员！仓库地址：https://github.com/Tyilo/insert_dylib
====================

/Applications/iShot.app/Contents/Frameworks/PTHotKey.framework/Versions/A/PTHotKey 目标文件已经存在. 要重写他吗? [y/n] y
这是一个FAT格式二进制,携带 2 个架构的代码(Intel/Apple Silicon ARM64).
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
添加 LC_LOAD_DYLIB 指令到通用架构, 应用程序：/Applications/iShot.app/Contents/Frameworks/PTHotKey.framework/Versions/A/PTHotKey。

_**但是：运行时终止的**_
Last login: Fri Jul 28 11:19:18 on ttys001
/Applications/iShot.app/Contents/MacOS/iShot ; exit;                            
mandyleigh@MacMiniWork ~ % /Applications/iShot.app/Contents/MacOS/iShot ; exit;
2023-07-28 11:22:43.804 iShot[4643:43844] ==== AppName is [cn.better365.ishot],Version is [2.3.8], myAppCFBundleVersion is [20230711001].
2023-07-28 11:22:43.804 iShot[4643:43844] ==== 当前App是 cn.better365.ishot 输入的App名称是 cn.better365.ishot, 是否需要注入? 需要注入.
2023-07-28 11:22:43.804 iShot[4643:43844] 当前CPU类型是 x86_64
2023-07-28 11:22:43.804 iShot[4643:43844] ==== 正在Hook Ptr 0x10006d23e
2023-07-28 11:22:43.804 iShot[4643:43844] ==== 模块序号:0,模块名称: /Applications/iShot.app/Contents/MacOS/iShot,获取到模块偏移: 0xfdbb000, 最终地址为0x10fe2823e
zsh: killed     /Applications/iShot.app/Contents/MacOS/iShot

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by QiuChenly** [comment]
谁让你双击运行/Applications/iShot.app/Contents/MacOS/iShot 这个二进制的？

**Comment by fourcute** [comment]
> 运行崩溃跟你是macOS 14没有关系。先检查自己的SIP关闭状态。黑苹果直接去OC关，老白苹果强行上macOS14的自己找办法。

非常感谢楼主的回复， 我用M1 测试是可以用的， 提交的问题的机器是黑苹果，SIP也是关闭了（但是黑苹果关闭SIP情况和白的有点不同，csr-active-config不同数字SIP关闭的程度也不同🥹，我觉得是opencore 对SIP关闭问题或者我不会操作），至于老苹果上新系统，其实也是opencore，同样也会有这个问题的。

因为我在黑苹果上 注入Navicat Premium这个，是正常使用的，只是iShot 和 Parallels Desktop（其他我没用）不能运行，Parallels Desktop 停留在启动中（M1 还没升级18.3.2所以还没试验），所以才会请教的

PS：所有设备都是14.0 Beta版(23A5301g) 上运行使用

再次感谢楼主的回复😄

**Comment by QiuChenly** [comment]
这个问题之前群里有人遇到过，解决办法是完全关闭SIP即可。

**Comment by fourcute** [comment]
> 这个问题之前群里有人遇到过，解决办法是完全关闭SIP即可。

好的 谢谢您
