### ISSUE TITLE
omi 录屏专家 M系列芯片支持了吗?

### ISSUE THREAD

**Issue by hibisicus** [QiuChenlyOpenSource/InjectLib#6]
我用旧项目的教程,破解OMI 录屏专家,但是破解完毕后,提示软件无法打开,请问这个现在的脚本支持这个了吗

**Comment by zhucp18** [comment]
没有，可以时刻关注项目的 [readme.md](https://github.com/QiuChenlyOpenSource/InjectLib#readme) **App兼容性** 里大佬已经写的很清楚了

**Comment by QiuChenly** [comment]
Update：
Omi录屏专家 1.3.1 (2023052501)  has been supported.

**Comment by hibisicus** [comment]
我是想要破解这个Omi录屏专家  现在可以支持了吗?
