### ISSUE TITLE
Fixing Parallels >18.1.1-53328 & criticism 

### ISSUE THREAD

**Issue by trueToastedCode** [QiuChenlyOpenSource/InjectLib#61]
**Protection**
For this crack to even run, people need to disable system integrity protection and library verification.... this is completely unnecessary and even dangerous.

One should rather just patch the binary directly and resign it with adhoc.

**It doesn't even work**
I've checked the assembly code of the latest version (aiming to support 18.3.2 53621), you're only hooking this "/usr/bin/codesign" thing and the "SignCheckerImpl" of the "prl_disp_service" (with the correct offsets for multiple versions).

In combination with a fake license this does indeed activate all versions of Parallels.

Unfortunately, using Parallels later than 18.1.1-53328, VM's won't start anymore (at least on arm64).
<img width="592" alt="Screenshot 2023-08-04 at 14 09 16" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/44642574/ebb9f4ea-05e6-4a2b-933b-24ec040e3806">

**Comment by QiuChenly** [comment]
ur right. but im didn't  find another method for OPEN SIP Environment to run Paralells. can only disable LibCheck & SIP OFF for that.

**Comment by trueToastedCode** [comment]
> ur right. but im didn't find another method for OPEN SIP Environment to run Paralells. can only disable LibCheck & SIP OFF for that.

Ok, I understand now, that any changed prl_* will result, in vm's not starting anymore, even if the Launcher starts and shows to be activated.

The dylib method is necessary, because it patches the code after it has been loaded into the memory.

It seems like, Parallels has implemented some checks that will fail, if some of the prl_* had been changed.

**Comment by QiuChenly** [comment]
Interesting. But after reboot system can stay the active status ？

**Comment by QiuChenly** [comment]
About the "then undoing it but with the modified prl_* in memor" i got some confused, can u talking details about it?thx.

**Comment by trueToastedCode** [comment]
> About the "then undoing it but with the modified prl_* in memor" i got some confused, can u talking details about it?thx.

I've made a repo: https://github.com/trueToastedCode/ParallelsLab/tree/%3E18.1.1-53328-lab
1. Install clean `18.3.2-53621`
2. Run `install.sh`
3. Start Parallels launcher (but not a VM)
4. Run `switch-stock.sh`
5. Run VM
6. After the launcher has been closed, you need to run `switch-patched.sh` and continue from step 3. again

**Comment by trueToastedCode** [comment]
> > About the "then undoing it but with the modified prl_* in memor" i got some confused, can u talking details about it?thx.
> 
> I've made a repo: https://github.com/trueToastedCode/ParallelsLab/tree/%3E18.1.1-53328-lab
> 
> 1. Install clean `18.3.2-53621`
> 2. Run `install.sh`
> 3. Start Parallels launcher (but not a VM)
> 4. Run `switch-stock.sh`
> 5. Run VM
> 6. After the launcher has been closed, you need to run `switch-patched.sh` and continue from step 3. again

File offset `0x1a638dc` and `0x1a63a54` of `prl_vm_app` are the two offsets, that do the signature validation for the `prl_disp_service` and cause any VM to crash, if the `prl_disp_service` binary had been signed with adhoc.

Overwriting them to just return 0 solves this issue.

1. We could hook them, but this still needs disabled library validation. 
2. One could also path this static binary, however we'd need to resign it. It uses `com.apple.vm.device-access` and `com.apple.vm.networking` entitlement, which Apple restricts only to some developers. Signing it without means the VM won't have Internet access, as well as no access to external devices.

Therefore an automation of my other solution by switching the binary would perhaps be the best solution.

**Comment by QiuChenly** [comment]
hi, about u 'File offset 0x1a638dc and 0x1a63a54 of prl_vm_app are the two offsets, that do the signature validation for the prl_disp_service and cause any VM to crash, if the prl_disp_service binary had been signed with adhoc.' this section, i did not find any result in my PD 18.3.2 Version, can u give me more infomation about it?

**Comment by nmweizi** [comment]
patch prl_disp_service和prl_vm_app后，把这俩签名。可以启动虚拟机，就是提示无网络。
>It uses com.apple.vm.device-access and com.apple.vm.networking entitlements

**Comment by QiuChenly** [comment]
无网络很致命，昨天我也找到这个函数了，但是研究一番发现苹果的天才设计导致必须要申请有效的开发者证书 必须要有这两个虚拟化框架使用权限才能使用。

**Comment by nmweizi** [comment]
是这个问题

**Comment by QiuChenly** [comment]
hi everyone, in PD 19.1, i am try patch can't to success, it's make me feel bad. who can give me any help and how to patch correct byteode?

**Comment by trueToastedCode** [comment]
> hi everyone, in PD 19.1, i am try patch can't to success, it's make me feel bad. who can give me any help and how to patch correct byteode?

They changed a bunch of stuff.. striking this time is prlsrvctl. It a license is installed, it previously didn't complain about login but now it does.

**Comment by QiuChenly** [comment]
thanks for u reply. too Sad, i am trying disassembled prl_disp_service and did not get any result yet, but i think the secret still in the "prl_disp_service" file.

**Comment by trueToastedCode** [comment]
> thanks for u reply. too Sad, i am trying disassembled prl_disp_service and did not get any result yet, but i think the secret still in the "prl_disp_service" file.

My first discovery: 
`arm64 sub_10035A8E8` seems to be an issue.

**Comment by QiuChenly** [comment]
i'll try it.

**Comment by trueToastedCode** [comment]
> i'll try it.

Good news 🎉 Found a new crack, tho need to do more testing.

**Comment by QiuChenly** [comment]
wow ！it's really unbelievable good news！ After the tests could u can given me more about the crack？I didn't find any other clues. thx

**Comment by trueToastedCode** [comment]
> wow ！it's really unbelievable good news！ After the tests could u can given me more about the crack？I didn't find any other clues. thx

It's published: https://github.com/trueToastedCode/ParallelsLab

**Comment by QiuChenly** [comment]
Thanks for your works! u r Genius!

**Comment by trueToastedCode** [comment]
> Thanks for your works! u r Genius!

Also got rid of the annoying launcher in latest commit now. I've instead hooked a core function, that get's called at the begining of the service and finishes when the service quits. This where the reset and patch can be automaticly done without additional scripts.

**Comment by QiuChenly** [comment]
hello! @trueToastedCode nice to meet you! u are reallllly genius! u make an very interesting works! but i noticed in your HookParallels.m, u using rd_route framework....ok, u are right,but the rd_route just working on  Intel, not for arm64. actually， i am has been re-write core code for my InjectLib, it now support arm64/Intel, just need little code, u can hook anything! if u need my new inject code ,email to me qiuchenly@outlook.com, i will very happy to share my unopened source code with u!

**Comment by trueToastedCode** [comment]
> hello! @trueToastedCode nice to meet you! u are reallllly genius! u make an very interesting works! but i noticed in your HookParallels.m, u using rd_route framework....ok, u are right,but the rd_route just working on Intel, not for arm64. actually， i am has been re-write core code for my InjectLib, it now support arm64/Intel (base DobbyFramework), just need little code, u can hook anything! if u need my new inject code ,email to me [qiuchenly@outlook.com](mailto:qiuchenly@outlook.com), i will very happy to share my unopensource code with u(it is free of charge!)!

Except I've updated rd_route for am64 - works wonderful (I do real live tests for all architectures). Nonetheless I'd be happy to checkout you're code as well 😃
