### ISSUE TITLE
iShot 2.3.9 显示激活，但是使用OCR还是会提示购买

### ISSUE THREAD

**Issue by wdkGitHub** [QiuChenlyOpenSource/InjectLib#62]
iShot 2.3.9 显示激活，但是使用OCR还是会提示购买

**Comment by wdkGitHub** [comment]
因特尔处理器

**Comment by fourcute** [comment]
<img width="918" alt="iShot_2023-08-09_下午2 20 25" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/38708797/20c29eab-3f09-4567-b084-5a2f562333b9">
 情况 （黑） 确实如此 （白）还没测试

**Comment by QiuChenly** [comment]
是这样的 这是伪造的授权信息有一一个地方可能没改对 下个版本再说吧

**Comment by QiuChenly** [comment]
不对啊 我这里没有任何问题
<img width="1792" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/24793281/c2790f1b-54f8-4d33-ab52-d93ff14bffa6">

**Comment by QiuChenly** [comment]
经测试没有问题，有问题的可能是你们自己没做对。

**Comment by QiuChenly** [comment]
这个弹窗应该只有第一次安装会出现一次 我找了几个arm/intel测试都没问题

**Comment by wdkGitHub** [comment]
我还卸载了重装试了两次，那我再试试看

**Comment by wdkGitHub** [comment]
app 是苹果商店下载的，用App Cleanner & Uninstaller 卸载了重新装 还是不行。 执行 sudo ruby main.rb 后 ，ishot 快捷键配置信息会被重置，保存位置也被重置，不知道是不是正常现象。
<img width="836" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12813051/c93f8876-ce28-409e-bda8-67089ce76085">
![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/12813051/b45400b1-047f-4556-9fac-472c03d034cb)
<img width="1087" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12813051/3d9a9717-da3d-408b-92cc-40efdda03206">

**Comment by wdkGitHub** [comment]
系统设置赋予的录屏权限也同时被重置

**Comment by QiuChenly** [comment]
@所有人
已确认问题所在，是因为每一台不同的设备加密的解密key分别不同。已经通过hook解密函数解决此问题，稍后将提交此解决方案。
