### ISSUE TITLE
App Cleaner & Uninstaller ARM版本 需求

### ISSUE THREAD

**Issue by fourcute** [QiuChenlyOpenSource/InjectLib#63]
如果版主有🈳的话 可以处理一下App Cleaner & Uninstaller ARM 版本就好了

现在只有版主的版本可以不跳出广告，其他 的版本都是有广告的，虽然也可以用的

感谢版主阅读
黑白苹果各一的人😄
「App Cleaner & Uninstaller | 8.2.2 | ❌ | ✅ | ⏳ | ARM64懒得弄了」

**Comment by wdkGitHub** [comment]
好像需要给大佬提供什么文件，软件安装包还是什么  具体不清楚
