### ISSUE TITLE
surge 的模块功能不可用

### ISSUE THREAD

**Issue by Undifinedu** [QiuChenlyOpenSource/InjectLib#64]
surge版本：5.3.0（2367）
系统版本：13.5
从url添加诸如doh的module时点完下一步后无反应，仅显示内置模块。且无本地模块选项

**Comment by Undifinedu** [comment]
更正sgmodule文件放入配置文件同目录时，模块可见，怀疑文件夹权限导致无法下载到对应地址。

**Comment by Undifinedu** [comment]
更正sgmodule文件放入配置文件同目录时，模块可见，怀疑文件夹权限导致无法下载到对应地址。

**Comment by QiuChenly** [comment]
你可以试试正版有没有这个问题。
