### ISSUE TITLE
不支持M2芯片

### ISSUE THREAD

**Issue by tangdai** [QiuChenlyOpenSource/InjectLib#65]
大佬好，今天试了试在M2 mini上激活Office套件，注入后提示不支持该cpu，未激活成功。 有什么方法可以解决吗？ 不胜感激！

**Comment by QiuChenly** [comment]
没有日志截图你说g8啊

**Comment by tangdai** [comment]
![WechatIMG277](https://github.com/QiuChenlyOpenSource/InjectLib/assets/65808138/56156266-d5a2-4f72-a01f-9a0d5a50e4bf)

**Comment by QiuChenly** [comment]
运行截图 不是注入截图

**Comment by QiuChenly** [comment]
这个错误是不支持你的操作系统版本好像是 但是我最低支持10.13 你这个是不是下载过程中出现问题文件下错了啊

**Comment by tangdai** [comment]
应该不是系统问题，mac mini是13系统，注入里面提示的错误的CUP类型，也不是下载过程出错，我重新下载了2次都一样的结果，拷贝到我在m1 Mac Pro 14系统上Office和其他的都是正常激活。

**Comment by QiuChenly** [comment]
问题已解决。重新下载正常执行。
