### ISSUE TITLE
破解surge5脚本签名com.nssurge.surge-mac.helper失败: a required plist file or resource is malformed

### ISSUE THREAD

**Issue by hsingll** [QiuChenlyOpenSource/InjectLib#70]
我用的是Catalina，脚本里`xattr -c '/Applications/Surge.app'`我改成了`xattr -d com.apple.quarantine '/Applications/Surge.app'`别的没动，但是到签名com.nssurge.surge-mac.helper时失败了。
<img width="1069" alt="Snipaste_2023-08-19_00-56-22" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/26346635/1d38cb16-d2b6-4795-9679-32a3d2ff6053">

**Comment by QiuChenly** [comment]
你为什么不运行一下看看到底错没错呢

**Comment by hsingll** [comment]
> 你为什么不运行一下看看到底错没错呢

我尝试运行过了，本体能打开，增强模式需要这个helper会失败。我手动复制到/Library/PrivilegedHelperTools也不行。
<img width="420" alt="Snipaste_2023-08-19_10-32-10" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/26346635/8bc94fcf-c7df-4fca-a025-02636c84917f">

**Comment by hsingll** [comment]
> 你为什么不运行一下看看到底错没错呢

可以在互联网上找到错误原因是/Library/LaunchDaemons/com.nssurge.surge-mac.helper.plist没清除，但不适用我的情况，我是首次安装，并且/Library/LaunchDaemons/下没有com.nssurge.surge-mac.helper.plist。

**Comment by QiuChenly** [comment]
不是  那你为什么不运行一下App看看到底是不是真的错误呢？？？？打个提示你是怎么看成报错的呢？我搞不懂

**Comment by QiuChenly** [comment]
能不能下次提问题之前报告自己的详细系统环境操作过程软件版本？

**Comment by QiuChenly** [comment]
你要是搞不定就用别人打包好的。

**Comment by hsingll** [comment]
> 能不能下次提问题之前报告自己的详细系统环境操作过程软件版本？不要等我要什么才回复什么 到底是我提的问题还是你提的问题？

感谢你的回复和帮助，可是我确实在第一次提问时就已经提供了系统是Catalina和详细的报错截图。（我可能少截了一行消息，而该消息确实让我以为这是错误，而您在回复中告知了我这不是，谢谢您）
<img width="346" alt="Snipaste_2023-08-19_12-34-37" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/26346635/7822c188-75d4-4f7f-a720-2fa90dd54060">


我不可能把我自己尝试解决的每一种思路都写一遍，那对您又没有帮助还浪费您阅读的时间。
但是关键的信息我一直有提供的，例如脚本中脚本中使用`xattr -c '/Applications/Surge.app'`去除所有属性，而Catalina下xattr没有-c，所以我改成了`xattr -d com.apple.quarantine '/Applications/Surge.app'`
<img width="649" alt="Snipaste_2023-08-19_12-38-11" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/26346635/c6f2f82f-0ca5-4db3-b164-05541f62945a">


我还是听您的，直接使用已打包好的程序，感谢您在周末美好的时间对我提供无私的帮助，祝你享受美好的一天。

**Comment by sqiangcao99** [comment]
@hsingll 请问去哪下载已经打包好的程序？
