### ISSUE TITLE
PD 19.0  虛擬機啟動失敗

### ISSUE THREAD

**Issue by digitalhouse** [QiuChenlyOpenSource/InjectLib#78]
PD 19.0 M2 Pro
按照指示安裝好後先執行腳本
啟動虛擬機報錯
<img width="273" alt="截圖 2023-08-22 21 00 09" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/786348/4744cf2d-d821-4434-a62f-6c3097ad007e">

**Comment by kratos9394** [comment]
去tool里面启动Parallels_原始人_起洞.command

**Comment by digitalhouse** [comment]
> 去tool裡面啟動Parallels_原始人_起洞.command

已解決 謝謝
