### ISSUE TITLE
Adobe PhotoShop Beta 24.7 注入了却还是弹窗提醒购买

### ISSUE THREAD

**Issue by fenger-t** [QiuChenlyOpenSource/InjectLib#8]
Adobe PhotoShop Beta 24.7 注入了却还是弹窗提醒购买，不知道是什么原因，正式版24.5注入了就没有问题。

**Comment by kratos9394** [comment]
确实24.7没用

**Comment by QiuChenly** [comment]
在线版本，你登录账户了吗

**Comment by fenger-t** [comment]
登录账户了，就是今早从Creative Cloud刚点试用下载的版本，操作系统是Intel平台

**Comment by QiuChenly** [comment]
可能升级版本了，我回去查一下

**Comment by digitalhouse** [comment]
更新版本後一樣碰到彈出購買視窗
M1 MAX 有關閉SIP
之前破解使用正常
今天更新完重新破解彈出購買視窗

**Comment by QiuChenly** [comment]
通知所有人: PS beta 版本更新了，所以失效。
他的大版本号不会更新，但是小版本号会持续变化，请等待上传新文件。

**Comment by QiuChenly** [comment]
由于我无法下载M芯片版本的二进制，请各位上传最新的24.7 PhotoShop二进制文件，他通常位于：
/Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/MacOS/Adobe Photoshop 2023

尽可能使用百度网盘或者蓝奏云，国内无法使用Google云或者其他国际网络存储服务。

**Comment by digitalhouse** [comment]
> 由於我無法下載M晶片版本的二進制，請各位上傳最新的24.7 PhotoShop二進制檔案，他通常位於： /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/MacOS/Adobe Photoshop 2023
> 
> 儘可能使用百度網盤或者藍奏雲，國內無法使用Google雲或者其他國際網路儲存服務。

链接: https://pan.baidu.com/s/1LvuBAIJD3HlVU7ZmfUHvYA?pwd=cvbf 提取码: cvbf 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by QiuChenly** [comment]
Update：
Adobe Photoshop 版本: 24.7.0 20230612.m.2205 has been Supported。

**Comment by digitalhouse** [comment]
> Update： Adobe Photoshop 版本: 24.7.0 20230612.m.2205 has been Supported。

已可正常使用
