### ISSUE TITLE
Parallels 19 one click launch app not work

### ISSUE THREAD

**Issue by Drovosek01** [QiuChenlyOpenSource/InjectLib#80]
I launched `Parallels_原始人_起洞.command` then type `y` and pressed Enter button then type my password and pressed Enter. After that I opened Applications folder and launched `启动_PD.app` and see error:

![image](https://github.com/QiuChenlyOpenSource/InjectLib/assets/29478700/38f8ad4f-0986-4c65-91ad-db7bb35c3bc3)

I little research contents this app and if I write my password in file `document.wflow` on line 66 that text `INPPUT=""` replaced to `INPPUT="mypassword"` save the file and relaunch `启动_PD.app` it work without errors.

Maybe I doing something wrong or script for generate app for on click launch Parallels Desktop need fix.

Thank you for the cracks.

**Comment by QiuChenly** [comment]
thaz too sad. it's time for say goodbye.
![Screenshot_20230823-082556_QQ邮箱](https://github.com/QiuChenlyOpenSource/InjectLib/assets/24793281/471dde44-6bd7-453c-8e8a-a88e0bc5d1c8)

**Comment by ShinjoKurumi** [comment]
Alludo 是这样的

**Comment by ChangKx11** [comment]
您好，我已收到您的邮件。

**Comment by ChangKx11** [comment]
您好，我已收到您的邮件。
