### ISSUE TITLE
最新版Surge5.3.1 (2379)和（2377）都试了， 用了原神_启动破姐之后，不能在线安装模块 已经关闭SIP

### ISSUE THREAD

**Issue by himonster1** [QiuChenlyOpenSource/InjectLib#84]
试过卸载干净重新安装 未破解情况下 模块功能正常 可以在线安装

破解后 无法在线安装 就是通过URL安装不了 点了安装没用

求大佬修复啊啊啊啊~ 阿里嘎多

**Comment by xiaxianxue** [comment]
這個問題已經說過了，在線模組的功能，有使用到iCloud同步的SDK，hack過後就不能使用了，你可以手動下載模組，再本地加載模組。

**Comment by QiuChenly** [comment]
你这种情况我还是真没见过，这样吧，你先到手机应用商店里，打开搜索，输入“原神”，然后点击下载安装，运行。输入你的手机号，点击立即注册输入验证码登录原神。

**Comment by Cowboy-Shuai** [comment]
把[.sgmodule]后缀的模块下载下来后，手动复制到下面路径试试
`~/Library/Application Support/com.nssurge.surge-mac/Installed`

**Comment by QiuChenly** [comment]
将配置目录重新🔝，可以正常在线安装模块。
