### ISSUE TITLE
误报 - Navicat Premium16.2.2 破解无效

### ISSUE THREAD

**Issue by kailuo99** [QiuChenlyOpenSource/InjectLib#9]
执行多次，重新打开还是显示试用未注册。apple M2.  13.4 (22F66)

**Comment by QiuChenly** [comment]
什么版本 从哪下的

**Comment by kailuo99** [comment]
16.2.2 官网下载的

**Comment by kailuo99** [comment]
哦哦，好吧 ！😓

**Comment by QiuChenly** [comment]
> 16.2.2 官网下载的

我这里标了只支持应用商店的版本，你应该用应用商店的版本尝试

**Comment by kailuo99** [comment]
支持那太好了，🙏🙏🙏。我现在试试

**Comment by nszy007** [comment]
> 



> > 16.2.2 官网下载的
> 
> 我这里标了只支持应用商店的版本，你应该用应用商店的版本尝试，我标错了，这个支持arm64

商店版本好似只有 intel 的，我用 hopper 打开过没有 arm 的代码
