### ISSUE TITLE
Surge 5.3.2 (2393) + Sonoma 异常

### ISSUE THREAD

**Issue by shirok1** [QiuChenlyOpenSource/InjectLib#91]
GUI 会在不定时间后闪退，有时候会自动重启有时候不会。

使用一键脚本破解。

**Comment by shirok1** [comment]
Dashboard 不受影响。

**Comment by QiuChenly** [comment]
该问题已标记，晚上将会修复。
操作系统和软件环境，还有控制台的崩溃日志发过来。

**Comment by shirok1** [comment]
Surge 5.3.2 (2393)

使用增强模式

后台的网络相关程序有

- ClashX Pro 1.118.0.1，未开启系统代理、增强模式
- WireGuard 1.0.16 (27) App Store 版，开启了一个仅本地地址的 VPN
- Tailscale 1.48.1 App Store 版，未启用

日志我希望能私发给你，方便使用邮箱吗

**Comment by QiuChenly** [comment]
qiuchenly@outlook.com

**Comment by shirok1** [comment]
> [qiuchenly@outlook.com](mailto:qiuchenly@outlook.com)

已发送。

**Comment by shirok1** [comment]
系统版本是 Sonoma 14.0 (23A339)

**Comment by QiuChenly** [comment]
这是运行日志  崩溃日志在哪呢？

**Comment by QiuChenly** [comment]
崩溃日志只有几百k 发的不对！

**Comment by shirok1** [comment]
<img width="604" alt="Screenshot 2023-09-21 at 19 04 03" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12044683/986ab8f5-823e-49e0-9a49-1a6cf3c7a81f">

我只找到了这些日志，崩溃日志是在其他地方吗？有时候闪退重启之后会显示从崩溃中恢复，有时候不会显示。

**Comment by QiuChenly** [comment]
控制台....有个app就叫控制台....

**Comment by shirok1** [comment]
<img width="834" alt="Screenshot 2023-09-21 at 19 17 34" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12044683/dc324d1b-493f-402d-9dea-ba11a8265663">

我记得从来就没触发过系统自带的应用崩溃提醒

**Comment by QiuChenly** [comment]
不会 强制闪退会有日志的

**Comment by shirok1** [comment]
可能是我描述有误，是使用一段时间之后自己退出，不是那种无法启动、系统报崩溃

**Comment by shirok1** [comment]
<img width="1552" alt="Screenshot 2023-09-21 at 20 20 35" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12044683/11dd0846-6ba0-4907-884c-9e3ded5b5750">
<img width="1552" alt="Screenshot 2023-09-21 at 20 25 19" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12044683/f5d9481c-7067-4e8e-8e0e-4bc94e8f7876">

**Comment by QiuChenly** [comment]
知道问题出在哪了，helper的问题。

**Comment by shirok1** [comment]
<img width="1552" alt="Screenshot 2023-09-21 at 21 14 44" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12044683/e66b384c-4375-4b48-a0e7-0db7b91dc733">

需要这个吗

**Comment by QiuChenly** [comment]
不用，这个问题Crash Report其实有报告。

**Comment by QiuChenly** [comment]
没有复现成功。
补丁没有问题，我直升最新测试版本2393，运行8+hrs并未有任何闪退和退出问题。

可能出现的问题：helper版本不匹配 
建议的解决方案：用BohuCleaner卸载Surge和删除Surge Helper重新安装后用补丁注入。

<img width="1096" alt="image" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/24793281/6e719207-7689-44a6-8a22-95ae5af73bde">

**Comment by Attiv** [comment]
可以试试完全卸载重装， 我也是这个版本，MAC14，卸载重装后没问题

**Comment by kratos9394** [comment]
BuhoCleaner 跟surge注入完就意外退出，sonoma

**Comment by teochen** [comment]
呃我今天也出现这个问题了，重启后无法打开。

**Comment by QiuChenly** [comment]
不知道你们什么情况 我这里运行正常 sip开启 ventura 最新5.33

**Comment by teochen** [comment]
Ven系统的时候我也可以正常使用。
我是在升级到sonoma后，第一次启动还可以用，再重启后就打不开了。
试过卸载干净，装官方版本可以打开，干净卸载后用脚本再次注入后，就又提示无法打开了😂

**Comment by kratos9394** [comment]
黑苹果要把amfi=0x80换成amfipassbeta，surge是好了，但是infuse注入之后打开以前的东西就提示密码错误，也没有icloud同步

**Comment by shirok1** [comment]
<img width="628" alt="Screenshot 2023-09-29 at 17 54 10" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/12044683/0a5d2eef-1c36-4a57-a073-00280adb8848">

**Comment by shirok1** [comment]
找你说的下了 Surge-5.3.3-2395-99df46127616e4b853821b5812b53193 结果更逆天

**Comment by shirok1** [comment]
Crash 也没找到

**Comment by QiuChenly** [comment]
你是m系，特征码已经发生了改变，所以会弹出来，但是问题不大，这是我的兜底策略，app还能正常用

**Comment by wejudging** [comment]
我也是遇到了相同的问题，莫名其妙重启，用的是目前最新公版的macos14.0系统！通过升级14.1 public的beta3系统，就解决了！应该是苹果系统的原因，目前已解决！！！！

**Comment by wejudging** [comment]
重新安装后又和之前一样闪退了！
