### ISSUE TITLE
[IQ Issues] 最近早上起来🐮🐮梆硬，怎么解决？

### ISSUE THREAD

**Issue by NaCoLiu** [QiuChenlyOpenSource/InjectLib#94]
玩原神玩的

**Comment by liangzad** [comment]
嘎了就彻底解决了

**Comment by QiuChenly** [comment]
这个情况还真没见过。这样吧，你先在羽丘一年A班或者天文部寻找“高松灯”发现后后立即翻她封面是红花的笔记本并找到歌曲“春日影”，询问她歌曲的由来并邀请她一起组乐队，并在她拒绝后告诉她“只要好好努力避免重蹈覆辙不就好了吗”，在她同意后寻找她的前队友一起组队（丰川祥子除外），最后在你们的第一场live中演奏“春日影”。

**Comment by NaCoLiu** [comment]
> 这个情况还真没见过。这样吧，你先在羽丘一年A班或者天文部寻找“高松灯”发现后后立即翻她封面是红花的笔记本并找到歌曲“春日影”，询问她歌曲的由来并邀请她一起组乐队，并在她拒绝后告诉她“只要好好努力避免重蹈覆辙不就好了吗”，在她同意后寻找她的前队友一起组队（丰川祥子除外），最后在你们的第一场live中演奏“春日影”。

俺不是偷，俺是拾勒。

**Comment by Cowboy-Shuai** [comment]
割以永治！

**Comment by NaCoLiu** [comment]
> 割以永治！

那你给我康康你寥寥的地方
