### ISSUE TITLE
tableplus新版似乎无效

### ISSUE THREAD

**Issue by ijry** [QiuChenlyOpenSource/InjectLib#95]
操作环境：macOS14.0(macbook air 2020 m1)
操作步骤：
1、brew install tableplus（版本5.4.2 build506）
2、打开tableplus尝试打开三个TAB出现弹窗
3、下载InjectLib
4、解压后双击原神原神_启动.command
5、监测到tableplus根据提示输入y
6、提示已完成注入再次打开tableplus验证，发现还是有超过3个TAB弹窗。
<img width="636" alt="iShot_2023-10-07_17 44 08" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/3102798/9c1f056d-c14d-4977-8ad1-0ce118156200">
<img width="543" alt="iShot_2023-10-07_17 44 39" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/3102798/963636b8-e5f8-46b8-bfaa-385ac20e337d">

**Comment by ijry** [comment]
切换到Rosetta运行注入是有效的

**Comment by QiuChenly** [comment]
你好 我们已经注意到你的问题，并初步确认是arm64的问题。

由于我们尚无能力购买M芯片的笔记本电脑，所以无法第一时间测试结果。

请卖掉你的ARM本重新购买Intel本以彻底解决此问题。

**Comment by ijry** [comment]
> 你好 我们已经注意到你的问题，并初步确认是arm64的问题。
> 
> 由于我们尚无能力购买M芯片的笔记本电脑，所以无法第一时间测试结果。
> 
> 请卖掉你的ARM本重新购买Intel本以彻底解决此问题。

没毛病哈哈，我才卖掉intel淘的m1不到半个月。

**Comment by LoveJessyChen** [comment]
运行rosetta模式 解决问题

**Comment by QiuChenly** [comment]
此问题已解决。
