### ISSUE TITLE
Adobe Acrobat Pro 23.006.20320 patch work only when SIP off

### ISSUE THREAD

**Issue by Drovosek01** [QiuChenlyOpenSource/InjectLib#99]
Adobe Acrobat Pro 23.006.20320 patch work only when SIP off

Also tested patches for Adobe 2024 - Illustrator, AFter Effects, Media Encoder, Premiere Pro, InDesign, InCopy and after apply patch and launch apliations it still ask paid subscription on my Adobe account. It happend with and without Rosetta.

Tested on macOS Ventura 13.6 M1

**Comment by QiuChenly** [comment]
u known, im not haven M series,so crack not work for ARM

**Comment by LoveJessyChen** [comment]
Work properly for arm, but I only tested it only when sip disabled.

**Comment by QiuChenly** [comment]
if have more problem,pls open new issues.
